import { AdminAccessGate, AdminShell } from "@/components/AdminShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, Globe2, LockKeyhole, PauseCircle, PlayCircle, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const availability: Array<"available" | "unavailable" | "coming_soon" | "requires_configuration"> = ["available", "unavailable", "coming_soon", "requires_configuration"];
const readable = (value: string) => value.replace(/_/g, " ");

export default function AdminCountriesPage() { return <AdminAccessGate><CountriesContent /></AdminAccessGate>; }
function CountriesContent() {
  const operations = trpc.admin.countryOperations.useQuery(); const utils = trpc.useUtils(); const [selectedId, setSelectedId] = useState<number | null>(null);
  const lifecycle = trpc.admin.setCountryLifecycle.useMutation({ onSuccess: () => { void utils.admin.countryOperations.invalidate(); toast.success("Country lifecycle updated."); }, onError: error => toast.error(error.message) });
  const policy = trpc.admin.saveCountryPolicy.useMutation({ onSuccess: () => { void utils.admin.countryOperations.invalidate(); toast.success("Country policy version saved."); }, onError: error => toast.error(error.message) });
  const countries = operations.data ?? []; const selected = countries.find(country => country.id === selectedId) ?? countries[0];
  const saveConfiguredPolicy = () => { if (!selected) return; policy.mutate({ countryId: selected.id, policyVersion: `country-${selected.iso2.toLowerCase()}-${Date.now()}`, signupAvailability: selected.availability.signup, discoveryAvailability: selected.availability.discovery, verificationAvailability: selected.availability.verification, paymentAvailability: selected.availability.payment, notificationAvailability: selected.availability.notifications, phoneVerificationAvailability: selected.availability.phoneVerification, supportedLocaleCodes: ["en"], supportedNotificationChannels: ["in_app"], privacyConfiguration: { locationDefault: "country", exactLocation: "never_exposed", ipDerivedPublicLocation: "never" }, verificationConfiguration: { mode: "manual_review_or_future_provider", provider: "not_configured" }, paymentConfiguration: { provider: "not_configured", exchangeRates: "not_configured" }, activate: false }); };
  return <AdminShell eyebrow="Country operations" title="Countries & diaspora readiness" description="Country access is a controlled rollout, not a marketing claim. This workspace exposes only policy-safe availability states and aggregate operational context. It never claims legal compliance, data residency, active payment providers, SMS delivery, exchange-rate conversion, or automated verification where those capabilities are not configured.">
    <section className="mt-8 grid gap-6 xl:grid-cols-[1.25fr_.75fr]">
      <div className="space-y-4">{operations.isLoading ? <div className="h-80 animate-pulse rounded-[1.5rem] bg-forest/8" /> : operations.error ? <div className="surface-card text-sm text-destructive">{operations.error.message}</div> : countries.map(country => <article key={country.id} className="surface-card"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex gap-3"><div className="icon-plate"><Globe2 size={20} /></div><div><p className="font-display text-2xl text-ink">{country.displayName}</p><p className="mt-1 text-xs text-muted-foreground">{country.iso2} · {country.region} · {country.defaultTimezone} · {country.memberCount} member records</p></div></div><div className="flex flex-wrap gap-2"><Badge className="badge-quiet">{readable(country.lifecycleStatus)}</Badge><Badge className={country.active ? "border-0 bg-emerald-50 text-emerald-700" : "border-0 bg-forest/5 text-muted-foreground"}>{country.active ? "active" : "not active"}</Badge></div></div><div className="mt-5 grid grid-cols-2 gap-2 text-xs sm:grid-cols-3"><Status label="Signup" value={country.availability.signup} /><Status label="Discovery" value={country.availability.discovery} /><Status label="Verification" value={country.availability.verification} /><Status label="Payment" value={country.availability.payment} /><Status label="Notifications" value={country.availability.notifications} /><Status label="Phone verification" value={country.availability.phoneVerification} /></div><div className="mt-5 flex flex-wrap gap-3"><Button variant="outline" className="border-forest/15 text-forest" onClick={() => setSelectedId(country.id)}>Review policy</Button>{country.lifecycleStatus === "active" ? <Button variant="outline" className="border-gold/40 text-gold-dark" disabled={lifecycle.isPending} onClick={() => lifecycle.mutate({ countryId: country.id, lifecycleStatus: "paused" })}><PauseCircle size={16} /> Pause rollout</Button> : country.lifecycleStatus === "paused" ? <Button className="btn-forest" disabled={lifecycle.isPending} onClick={() => lifecycle.mutate({ countryId: country.id, lifecycleStatus: "active" })}><PlayCircle size={16} /> Resume if policy permits</Button> : null}</div></article>)}</div>
      <aside className="space-y-6">{selected ? <section className="surface-card"><p className="eyebrow text-gold-dark">Country policy draft</p><h2 className="mt-2 font-display text-3xl text-ink">{selected.displayName}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">A policy version records availability honestly. Saving a draft does not activate a provider or bypass the country lifecycle.</p><div className="mt-5 space-y-3"><State label="Signup" state={selected.availability.signup} /><State label="Discovery" state={selected.availability.discovery} /><State label="Verification" state={selected.availability.verification} /><State label="Payments" state={selected.availability.payment} /><State label="Notifications" state={selected.availability.notifications} /><State label="Phone verification" state={selected.availability.phoneVerification} /></div><Button className="mt-6 w-full btn-forest" disabled={policy.isPending} onClick={saveConfiguredPolicy}>{policy.isPending ? "Saving…" : "Save a policy draft"}</Button></section> : null}<section className="surface-card"><ShieldCheck className="text-gold-dark" size={22} /><h2 className="mt-4 font-display text-2xl text-ink">No country prestige.</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Country is logistical and cultural context only. It cannot become a Trust Score, safety severity input, Premium benefit, popularity signal, or recommendation ranking factor.</p></section><section className="surface-card"><LockKeyhole className="text-gold-dark" size={22} /><h2 className="mt-4 font-display text-2xl text-ink">Activation is deliberate.</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Lifecycle moves are audited. Active status requires an active policy, while payment, phone verification, and provider states remain explicit until separately configured.</p></section></aside>
    </section>
  </AdminShell>;
}
function Status({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-forest/10 bg-white px-3 py-2"><p className="text-[10px] font-semibold uppercase tracking-[.12em] text-muted-foreground">{label}</p><p className="mt-1 font-semibold capitalize text-ink">{readable(value)}</p></div>; }
function State({ label, state }: { label: string; state: string }) { return <div className="flex items-center justify-between gap-3"><p className="text-sm font-medium text-ink">{label}</p><Badge className="badge-quiet">{readable(state)}</Badge></div>; }
