import { AdminAccessGate, AdminShell } from "@/components/AdminShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { StatePanel, StateSkeleton } from "@/components/StatePanel";
import { trpc } from "@/lib/trpc";
import { CircleAlert, ShieldCheck, UsersRound } from "lucide-react";
import { toast } from "sonner";

export default function AdminFamilyCirclePage() {
  const metadata = trpc.admin.familyMetadata.useQuery();
  const utils = trpc.useUtils();
  const restrict = trpc.admin.restrictFamilyParticipant.useMutation({ onSuccess: () => { void utils.admin.familyMetadata.invalidate(); toast.success("Family Circle access was restricted and audited."); }, onError: () => toast.error("Family Circle access could not be restricted. Please try again.") });
  const reviewWali = trpc.admin.reviewWaliGuardian.useMutation({ onSuccess: () => { void utils.admin.familyMetadata.invalidate(); toast.success("The Wali/Guardian verification status was recorded and audited."); }, onError: () => toast.error("The Wali/Guardian review could not be recorded. Please try again.") });

  return <AdminAccessGate><AdminShell eyebrow="Trust & Safety · Family Circle" title="Family Circle oversight" description="Review relationship metadata only when support or safety work requires it. Private messages, voice notes, verification documents, readiness criteria, and internal compatibility calculations are not available in this workspace.">
    <section className="surface-card mt-8"><div className="flex items-start gap-3"><div className="icon-plate"><ShieldCheck size={19} /></div><div><p className="text-sm font-semibold text-ink">Operational boundary</p><p className="mt-1 text-sm leading-6 text-muted-foreground">Family participation is advisory. Restricting access revokes Family Circle permissions and active shared-match views; it never changes a member-to-member match or substitutes for a member’s own consent.</p></div></div></section>
    <section className="mt-7 space-y-4">{metadata.isLoading ? <StateSkeleton label="Loading Family Circle oversight records…" /> : metadata.isError ? <StatePanel kind="error" title="Family Circle oversight is unavailable right now." description="No relationship metadata or access state has been changed. Please try again." action={<Button onClick={() => metadata.refetch()} className="btn-forest">Try again</Button>} /> : metadata.data?.length ? metadata.data.map(item => <article key={item.id} className="surface-card"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><Badge className="badge-quiet">{item.relationship === "wali_guardian" ? "Wali/Guardian" : "Parent"}</Badge><Badge variant="outline" className="border-forest/15 text-forest">{item.status.replace(/_/g, " ")}</Badge>{item.relationship === "wali_guardian" ? <Badge variant="outline" className="border-gold/30 bg-gold/10 text-ink">Wali status: {item.waliVerificationStatus.replace(/_/g, " ")}</Badge> : null}</div><h2 className="mt-4 font-display text-2xl text-ink">Family Circle record #{item.id}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Member profile reference #{item.memberProfileId}. Created {new Date(item.createdAt).toLocaleDateString()}.</p></div><div className="flex flex-wrap gap-2">{item.relationship === "wali_guardian" ? <><Button size="sm" variant="outline" disabled={reviewWali.isPending} onClick={() => reviewWali.mutate({ familyLinkId: item.id, decision: "verified" })}>Mark verified</Button><Button size="sm" variant="outline" disabled={reviewWali.isPending} onClick={() => reviewWali.mutate({ familyLinkId: item.id, decision: "unverified" })}>Mark unverified</Button></> : null}<Button size="sm" variant="outline" className="text-destructive hover:text-destructive" disabled={restrict.isPending || ["suspended", "removed", "revoked"].includes(item.status)} onClick={() => restrict.mutate({ familyLinkId: item.id, reason: "Trust & Safety access restriction" })}>Restrict access</Button></div></div></article>) : <StatePanel kind="empty" title="No Family Circle metadata needs review." description="Family Circle relationships appear here only as scoped metadata. Operational review does not unlock private member content." />}</section>
    <section className="surface-card mt-7"><div className="flex gap-3"><CircleAlert className="shrink-0 text-gold-dark" size={19} /><p className="text-sm leading-6 text-muted-foreground">Use the existing Trust & Safety report workflow for family participant concerns. This view supports controlled access restriction only; it does not create a parallel moderation system.</p></div></section>
  </AdminShell></AdminAccessGate>;
}
