import { AdminAccessGate, AdminShell } from "@/components/AdminShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { StatePanel, StateSkeleton } from "@/components/StatePanel";
import { trpc } from "@/lib/trpc";
import { CircleAlert, ShieldCheck, Video } from "lucide-react";
import { toast } from "sonner";

export default function AdminConnectionReviewsPage() {
  const queue = trpc.admin.connectionReviewQueue.useQuery();
  const utils = trpc.useUtils();
  const decide = trpc.admin.decideConnectionReview.useMutation({ onSuccess: () => { utils.admin.connectionReviewQueue.invalidate(); toast.success("The connection review was recorded and audited."); }, onError: error => toast.error(error.message) });
  const claim = trpc.admin.claimConnectionReview.useMutation({ onSuccess: () => { utils.admin.connectionReviewQueue.invalidate(); toast.success("The readiness case is now assigned to you."); }, onError: error => toast.error(error.message) });
  const escalate = trpc.admin.escalateConnectionReview.useMutation({ onSuccess: () => { utils.admin.connectionReviewQueue.invalidate(); toast.success("The readiness case was escalated and audited."); }, onError: error => toast.error(error.message) });
  return <AdminAccessGate><AdminShell eyebrow="Trust & Safety · connection readiness" title="Connection review" description="Review only escalated or policy-required readiness cases. This workspace does not display private message or voice-note content.">
    <section className="surface-card mt-8"><div className="flex items-start gap-3"><div className="icon-plate"><ShieldCheck size={19} /></div><div><p className="text-sm font-semibold text-ink">Decision boundary</p><p className="mt-1 text-sm leading-6 text-muted-foreground">Staff can approve, restrict, revoke, decline, or escalate a readiness case. A decision never creates a live call; provider access remains intentionally unconfigured.</p></div></div></section>
	    <section className="mt-7 space-y-4">{queue.isLoading ? <StateSkeleton label="Loading connection reviews…" /> : queue.isError ? <StatePanel kind="error" title="Connection reviews are unavailable right now." description="No review case has been shown. Please try again." action={<Button onClick={() => queue.refetch()} className="btn-forest">Try again</Button>} /> : queue.data?.length ? queue.data.map(item => <article key={item.id} className="surface-card"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><Badge className="badge-quiet">{item.status.replace(/_/g, " ")}</Badge>{item.reason ? <Badge variant="outline" className="border-gold/30 bg-gold/10 text-ink">{item.reason.replace(/_/g, " ")}</Badge> : null}{item.assignedReviewerUserId ? <Badge variant="outline" className="border-forest/20 text-forest">Claimed</Badge> : null}</div><h2 className="mt-4 font-display text-2xl text-ink">Readiness case #{item.id}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Connection state #{item.connectionStateId}. Review the controlled readiness record and any linked Trust & Safety facts—never private conversation content.</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" disabled={claim.isPending || Boolean(item.assignedReviewerUserId)} onClick={() => claim.mutate({ reviewId: item.id })}>Claim</Button><Button size="sm" variant="outline" disabled={escalate.isPending} onClick={() => escalate.mutate({ reviewId: item.id })}>Escalate</Button><Button size="sm" className="btn-forest" disabled={decide.isPending} onClick={() => decide.mutate({ reviewId: item.id, decision: "approved_voice" })}>Approve voice</Button><Button size="sm" variant="outline" disabled={decide.isPending} onClick={() => decide.mutate({ reviewId: item.id, decision: "approved_video" })}>Approve video</Button><Button size="sm" variant="outline" className="text-destructive hover:text-destructive" disabled={decide.isPending} onClick={() => decide.mutate({ reviewId: item.id, decision: "restricted" })}>Restrict</Button></div></div></article>) : <StatePanel kind="empty" title="No connection reviews await action." description="Healthy conversations are not manually reviewed by default. Cases appear only when configured policy, mutual video consent, an interaction-integrity hold, or an escalated safety pathway requires operational oversight." />}</section>
	    <section className="surface-card mt-7"><div className="flex gap-3"><CircleAlert className="shrink-0 text-gold-dark" size={19} /><p className="text-sm leading-6 text-muted-foreground">Member blocks, consent withdrawal, safety restrictions, suspension, interaction-integrity holds, and relevant hard-compatibility changes revoke enhanced communication immediately. Any later availability requires current policy checks and mutual consent again.</p></div></section>
  </AdminShell></AdminAccessGate>;
}
