import { AdminAccessGate, AdminShell } from "@/components/AdminShell";
import { Badge } from "@/components/ui/badge";
import { trpc } from "@/lib/trpc";
import { ClipboardCheck, Flag, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

export default function AdminPage() {
  const overview = trpc.admin.overview.useQuery();
  return <AdminAccessGate><AdminShell title="Trust & Safety overview" description="A role-aware operational workspace. Queue access, document access, and actions are controlled by verification and Trust & Safety scopes.">{overview.isLoading ? <div className="mt-8 h-44 animate-pulse rounded-[1.5rem] bg-forest/8" /> : overview.error ? <div className="mt-8 rounded-2xl border border-destructive/20 bg-destructive/5 p-5 text-sm text-destructive">{overview.error.message}</div> : <><div className="mt-9 grid gap-5 md:grid-cols-3"><AdminStat label="Verification queue" value={overview.data?.verificationQueue.length ?? 0} text="Submitted, in review, or escalated" /><AdminStat label="Open reports" value={overview.data?.reportsQueue.length ?? 0} text="Operationally active cases" /><AdminStat label="Operational scopes" value={overview.data?.scopes.length ?? 0} text={(overview.data?.scopes ?? []).join(" · ") || "No scope assigned"} /></div><div className="mt-8 grid gap-6 xl:grid-cols-2"><OverviewPanel title="Identity verification" text="Review private identity cases with explicit document access logging and structured decisions." icon={ClipboardCheck} href="/admin/verification" count={overview.data?.verificationQueue.length ?? 0} /><OverviewPanel title="Trust & Safety reports" text="Manage reports with assignment, notes, proportionate actions, and auditable outcomes." icon={Flag} href="/admin/reports" count={overview.data?.reportsQueue.length ?? 0} /></div><div className="mt-8 rounded-[1.5rem] border border-gold/35 bg-gold/10 p-6"><p className="font-display text-2xl text-ink">High-impact actions remain constrained</p><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">Permanent bans, permanent deletion, sensitive exports, and critical security configuration changes are not exposed in this Phase 2 workspace. They are reserved for a future dual-authorization workflow.</p></div></>}</AdminShell></AdminAccessGate>;
}

function AdminStat({ label, value, text }: { label: string; value: string | number; text: string }) { return <div className="surface-card"><p className="text-sm font-medium text-muted-foreground">{label}</p><p className="mt-3 font-display text-5xl text-ink">{value}</p><p className="mt-2 line-clamp-2 text-xs text-muted-foreground">{text}</p></div>; }
function OverviewPanel({ title, text, icon: Icon, href, count }: { title: string; text: string; icon: React.ComponentType<{ size?: number }>; href: string; count: number }) { return <Link href={href} className="action-tile"><div className="flex items-center justify-between"><div className="icon-plate"><Icon size={19} /></div><Badge className="badge-quiet">{count} active</Badge></div><h2 className="mt-6 font-display text-3xl text-ink">{title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p><p className="mt-5 text-sm font-semibold text-forest">Open operational queue</p></Link>; }
