import { MemberShell } from "@/components/MemberShell";
import { StatePanel, StateSkeleton } from "@/components/StatePanel";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, ChevronRight, Clock3, HeartHandshake, MessageCircle, ShieldCheck, UsersRound } from "lucide-react";
import { Link } from "wouter";
import { toast } from "sonner";

const readable = (value?: string | null) => value ? value.replace(/_/g, " ") : "Unavailable";

export default function ConnectionsPage() {
  const utils = trpc.useUtils();
  const profile = trpc.profile.mine.useQuery();
  const profileReady = profile.data?.eligibility?.profileComplete === true;
  const incoming = trpc.interests.incoming.useQuery(undefined, { enabled: profileReady });
  const outgoing = trpc.interests.outgoing.useQuery(undefined, { enabled: profileReady });
  const matches = trpc.matches.list.useQuery(undefined, { enabled: profileReady });
  const conversations = trpc.messaging.conversations.useQuery(undefined, { enabled: profileReady });
  const respond = trpc.interests.respond.useMutation({
    onSuccess: result => { void utils.interests.incoming.invalidate(); void utils.interests.outgoing.invalidate(); void utils.matches.list.invalidate(); void utils.messaging.conversations.invalidate(); toast.success(result.matched ? "Your mutual connection is ready for private conversation." : "The introduction was declined."); },
    onError: () => toast.error("That introduction is no longer available. Your list has not changed."),
  });
  const withdraw = trpc.interests.withdraw.useMutation({
    onSuccess: () => { void utils.interests.outgoing.invalidate(); toast.success("Your pending introduction request was withdrawn."); },
    onError: () => toast.error("That pending request is no longer available."),
  });

  const loading = profile.isLoading || (profileReady && (incoming.isLoading || outgoing.isLoading || matches.isLoading || conversations.isLoading));
  const unavailable = incoming.isError || outgoing.isError || matches.isError || conversations.isError;
  const conversationByMatch = new Map((conversations.data?.items ?? []).map(conversation => [conversation.matchId, conversation]));

  if (loading) return <MemberShell eyebrow="Connections" title="Your introductions and connections." description="Loading your private, server-authoritative relationship states."><StateSkeleton label="Loading your introductions and connections…" /></MemberShell>;
  if (profile.isError) return <MemberShell eyebrow="Connections" title="Your introductions and connections." description="Only current connection states are shown here."><StatePanel kind="error" title="Your profile status is unavailable right now." description="No interest, match, readiness, or message state has changed. Please retry before reviewing connections." action={<Button className="btn-forest" onClick={() => profile.refetch()}>Try again</Button>} /></MemberShell>;
  if (!profileReady) { const eligibility = profile.data?.eligibility; return <MemberShell eyebrow="Connections" title="Your introductions and connections." description="A completed profile is required before connection states can be shown."><StatePanel kind="empty" title={eligibility?.title || "Complete your profile before reviewing connections."} description={eligibility?.detail || "Finish your private profile foundation before introductions, mutual connections, and messages become available."} action={<Link href={eligibility?.photosRemaining ? "/app/photos" : "/app/onboarding"} className="btn-forest inline-flex items-center gap-2">{eligibility?.nextAction || "Complete profile"} <ChevronRight size={16} /></Link>} /></MemberShell>; }
  if (unavailable) return <MemberShell eyebrow="Connections" title="Your introductions and connections." description="Only current connection states are shown here."><StatePanel kind="error" title="Connections are unavailable right now." description="No interest, match, readiness, or message state has changed. Please retry when ready." action={<Button className="btn-forest" onClick={() => { void incoming.refetch(); void outgoing.refetch(); void matches.refetch(); void conversations.refetch(); }}>Try again</Button>} /></MemberShell>;

	  return <MemberShell eyebrow="Connections" title="Your introductions and connections." description="Review incoming and outgoing introductions, then continue only where a mutual connection is active. Readiness remains a separate, revocable choice.">
	    <section className="welcome-panel"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-sm font-semibold text-gold">Relationship state, without pressure</p><h2 className="mt-3 max-w-3xl font-display text-4xl leading-tight text-cream">Every next step stays mutual.</h2><p className="mt-4 max-w-3xl text-sm leading-6 text-cream">An interest request does not create a conversation. A mutual connection allows private messaging only while both the connection and its safety boundaries remain active.</p></div><Badge className="border border-gold/30 bg-cream/10 text-cream">{matches.data?.length ?? 0} mutual</Badge></div><div className="mt-7 flex flex-wrap gap-3"><Link href="/app/discover" className="btn-gold inline-flex items-center gap-2">Explore discovery <ChevronRight size={16} /></Link><Link href="/app/recommendations" className="inline-flex items-center gap-2 rounded-xl border border-cream/30 px-4 py-2.5 text-sm font-semibold text-cream hover:bg-cream/10">View recommendations</Link></div></section>

    <section className="mt-7 grid gap-5 xl:grid-cols-2"><InterestColumn title="Incoming introductions" icon={HeartHandshake} emptyTitle="No introduction is awaiting your choice." emptyDetail="When an eligible member sends an introduction, you can accept or decline it here. Nothing opens automatically." items={incoming.data ?? []} render={request => <article key={request.id} className="surface-card"><p className="eyebrow text-gold-dark">Received introduction</p><h3 className="mt-2 font-display text-2xl text-ink">Consider this request privately.</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{request.message || "No personal note was included. You can review this introduction on your own terms."}</p><div className="mt-5 flex flex-wrap gap-3"><Button className="btn-forest" disabled={respond.isPending} onClick={() => respond.mutate({ interestId: request.id, response: "accepted" })}>Accept introduction</Button><Button variant="outline" disabled={respond.isPending} onClick={() => respond.mutate({ interestId: request.id, response: "declined" })}>Decline</Button></div></article>} /><InterestColumn title="Outgoing introductions" icon={Clock3} emptyTitle="You have no outgoing introductions." emptyDetail="Discovery and recommendations remain available when your profile is eligible. A request remains private until the other member responds." items={outgoing.data ?? []} render={request => <article key={request.id} className="surface-card"><div className="flex items-start justify-between gap-3"><div><p className="eyebrow text-gold-dark">Introduction request</p><h3 className="mt-2 font-display text-2xl text-ink">{request.recipient?.displayName || "Bantabato member"}</h3></div><Badge variant="outline" className="border-forest/15 bg-cream text-forest">{readable(request.status)}</Badge></div><p className="mt-3 text-sm leading-6 text-muted-foreground">{request.status === "pending" ? "This request is awaiting a choice. You can withdraw it; no conversation is available yet." : request.status === "accepted" ? "This introduction became a mutual connection. Continue in your connections below." : "This request is no longer active. No new relationship state has been created."}</p>{request.status === "pending" ? <Button variant="outline" className="mt-5" disabled={withdraw.isPending} onClick={() => withdraw.mutate({ interestId: request.id })}>Withdraw request</Button> : null}</article>} /></section>

    <section className="mt-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow text-gold-dark">Mutual connections</p><h2 className="mt-2 font-display text-3xl text-ink">Continue only where it is available.</h2></div><Link href="/app/messages" className="inline-flex items-center gap-2 text-sm font-semibold text-forest hover:underline">All conversations <ChevronRight size={16} /></Link></div>{matches.data?.length ? <div className="mt-5 grid gap-4 lg:grid-cols-2">{matches.data.map(match => <ConnectionCard key={match.id} match={match} conversation={conversationByMatch.get(match.id)} />)}</div> : <StatePanel className="mt-5" kind="empty" title="No mutual connections yet." description="An accepted introduction appears here. Until then, you can explore eligible discovery profiles or review your outgoing requests." action={<Link href="/app/discover" className="btn-forest inline-flex items-center gap-2">Explore discovery <ChevronRight size={16} /></Link>} />}</section>
  </MemberShell>;
}

function InterestColumn({ title, icon: Icon, emptyTitle, emptyDetail, items, render }: { title: string; icon: React.ComponentType<{ size?: number }>; emptyTitle: string; emptyDetail: string; items: Array<any>; render: (item: any) => React.ReactNode }) { return <section><div className="flex items-center gap-3"><div className="icon-plate"><Icon size={19} /></div><div><p className="eyebrow text-gold-dark">Introductions</p><h2 className="font-display text-3xl text-ink">{title}</h2></div></div>{items.length ? <div className="mt-5 space-y-4">{items.map(render)}</div> : <StatePanel className="mt-5" kind="empty" title={emptyTitle} description={emptyDetail} />}</section>; }

function ConnectionCard({ match, conversation }: { match: any; conversation?: any }) {
  const readiness = trpc.readiness.status.useQuery({ conversationId: conversation?.id ?? 0 }, { enabled: Boolean(conversation?.id) && ["mutual_interest", "active", "paused", "reported", "restricted"].includes(conversation.status) });
  const state = conversation?.status === "active" ? "Communication available" : conversation ? readable(conversation.status) : "Mutual connection";
  const messageHref = conversation ? `/app/messages/${conversation.id}` : "/app/messages";
  return <article className="surface-card"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow text-gold-dark">Mutual connection</p><h3 className="mt-2 font-display text-2xl text-ink">{match.otherProfile?.displayName || "Bantabato member"}</h3></div><Badge className={conversation?.status === "active" ? "badge-quiet" : "border border-forest/15 bg-cream text-forest"}>{state}</Badge></div><p className="mt-3 text-sm leading-6 text-muted-foreground">{conversation?.unreadCount ? `${conversation.unreadCount} unread private message${conversation.unreadCount === 1 ? "" : "s"}.` : conversation ? "Private conversation state is shown here without exposing message content." : "This mutual connection is recorded. Conversation availability may update when the current relationship state allows it."}</p>{readiness.data ? <div className="mt-4 rounded-xl bg-cream/70 p-4"><div className="flex items-center gap-2"><ShieldCheck size={16} className="text-gold-dark" /><p className="text-sm font-semibold text-ink">Readiness: {readable(readiness.data.status)}</p></div><p className="mt-2 text-xs leading-5 text-muted-foreground">{readiness.data.explanation}</p></div> : readiness.isError ? <p className="mt-4 text-xs leading-5 text-muted-foreground">Connection readiness is unavailable right now. No consent or communication state changed.</p> : null}<div className="mt-5 flex flex-wrap gap-3"><Link href={messageHref} className="btn-forest inline-flex items-center gap-2"><MessageCircle size={16} />{conversation?.status === "active" ? "Open conversation" : "Review connection"}</Link><Link href={`/app/profile/${match.otherProfile?.id}`} className="inline-flex items-center gap-2 rounded-xl border border-forest/15 px-4 py-2.5 text-sm font-semibold text-forest hover:bg-forest/5"><UsersRound size={16} />View profile</Link></div></article>;
}
