import { PublicLayout } from "@/components/PublicLayout";
import { Button } from "@/components/ui/button";
import { Reveal, Stagger } from "@/components/ExperienceMotion";
import { ArrowRight, CheckCircle2, Globe2, HeartHandshake, LockKeyhole, MessageCircleHeart, ShieldCheck, UserRoundCheck, UsersRound } from "lucide-react";
import { Link } from "wouter";

const pillars = [
  { icon: ShieldCheck, title: "Trust before introductions", text: "Private identity review, clear member standards, and safety controls support a more deliberate beginning." },
  { icon: HeartHandshake, title: "Marriage with intention", text: "Thoughtful discovery replaces swiping, giving every introduction the attention it deserves." },
  { icon: UsersRound, title: "Family, by your choice", text: "Invite a trusted parent or wali when it feels right—without giving up your private space." },
];

const journey = [
  ["01", "Create your profile", "Begin with the essentials and keep your information in a private, member-controlled space."],
  ["02", "Prepare for review", "Follow the factual readiness steps, including private identity review and approved-photo requirements where applicable."],
  ["03", "Discover thoughtfully", "Explore considered profiles and preferences—not a public feed or swipe-first experience."],
  ["04", "Express interest", "Make an introduction respectfully. The other member remains free to decide."],
  ["05", "Connect when it is mutual", "Private conversation opens only after a mutual connection and any relevant access checks."],
  ["06", "Move toward marriage", "Continue at your pace, with optional Family Circle or Wali involvement under your control."],
] as const;

export default function Home() {
  return <PublicLayout>
    <main>
      <section className="hero-section overflow-hidden">
        <div className="hero-glow hero-glow-one" /><div className="hero-glow hero-glow-two" />
        <div className="container relative grid items-end gap-12 pb-16 pt-16 lg:grid-cols-[1.15fr_.85fr] lg:pb-24 lg:pt-24">
          <Reveal><div className="max-w-3xl"><div className="eyebrow"><span className="eyebrow-dot" /> Matrimony, with meaning</div><h1 className="hero-title">Where love<br />takes <em>root.</em></h1><p className="hero-copy">A private, marriage-first space for Gambians in The Gambia, Senegal, and the diaspora to meet with faith, clarity, and serious intention.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg" className="btn-gold h-12 px-6"><Link href="/register">Join Bantabato <ArrowRight size={17} /></Link></Button><Button asChild size="lg" variant="outline" className="h-12 border-forest/20 bg-transparent px-6 text-forest hover:bg-forest/5"><Link href="/how-it-works">How Bantabato works</Link></Button></div><p className="mt-6 flex items-center gap-2 text-sm text-forest/70"><LockKeyhole size={15} /> Private by default. Respectful by design.</p></div></Reveal>
          <Reveal delay="motion-delay-2"><div className="hero-card"><div className="hero-card-top"><p className="font-display text-2xl text-cream">A considered beginning</p><div className="hero-orbit"><div /><div /><div /></div></div><div className="mt-auto"><div className="divider-gold" /><p className="mt-5 text-sm leading-6 text-cream/70">A shared path begins with mutual respect, private identity review, and the freedom to move at your own pace.</p><div className="mt-5 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.14em] text-gold"><CheckCircle2 size={15} /> Designed for serious adults</div></div></div></Reveal>
        </div>
      </section>

      <section className="section-soft"><div className="container"><Reveal><div className="max-w-2xl"><p className="eyebrow text-gold-dark">Built around what matters</p><h2 className="section-title mt-4">A quieter, more dignified way to meet.</h2><p className="mt-5 max-w-xl leading-7 text-muted-foreground">Bantabato is built for adults seeking a meaningful marriage. Privacy choices, thoughtful discovery, manual review, and optional family involvement are designed to support a respectful journey—not rush it.</p></div></Reveal><Stagger className="mt-12 grid gap-5 md:grid-cols-3">{pillars.map(pillar => <article key={pillar.title} className="value-card"><div className="icon-plate"><pillar.icon size={22} /></div><h3 className="mt-7 font-display text-2xl text-ink">{pillar.title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{pillar.text}</p></article>)}</Stagger></div></section>

      <section className="bg-cream py-16 md:py-24"><div className="container"><Reveal><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow text-gold-dark">A deliberate journey</p><h2 className="section-title mt-4">From first profile to a meaningful connection.</h2><p className="mt-5 max-w-md leading-7 text-muted-foreground">Every stage has a purpose. There is no public social feed and no one-sided access to private conversations.</p><Button asChild variant="outline" className="mt-7 border-forest/20 bg-white text-forest hover:bg-forest/5"><Link href="/how-it-works">Explore each step <ArrowRight size={16} /></Link></Button></div><ol className="grid gap-3 sm:grid-cols-2">{journey.map(([number, title, text]) => <li key={number} className="rounded-2xl border border-forest/10 bg-white p-5 shadow-[0_12px_35px_rgba(21,58,45,.04)]"><span className="text-xs font-semibold tracking-[.15em] text-gold-dark">{number}</span><h3 className="mt-3 font-display text-2xl text-ink">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></li>)}</ol></div></Reveal></div></section>

      <section className="border-y border-forest/10 bg-white py-16 md:py-24"><div className="container grid gap-7 lg:grid-cols-3"><Reveal><article className="rounded-[1.5rem] bg-forest p-7 text-cream"><ShieldCheck size={23} className="text-gold" /><h2 className="mt-7 font-display text-3xl">Verification is one part of trust.</h2><p className="mt-4 text-sm leading-7 text-cream/72">An identity-reviewed badge only means an identity document has been manually approved. It is not a promise about character, compatibility, intentions, or safety.</p><Link href="/safety" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-gold">Understand verification <ArrowRight size={16} /></Link></article></Reveal><Reveal delay="motion-delay-1"><article className="rounded-[1.5rem] border border-forest/10 bg-cream p-7"><LockKeyhole size={23} className="text-gold-dark" /><h2 className="mt-7 font-display text-3xl text-ink">Privacy stays private.</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">Identity documents and private media do not appear in discovery, public stories, ordinary profiles, messages, or Family Circle information.</p><Link href="/privacy" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-forest">Explore privacy choices <ArrowRight size={16} /></Link></article></Reveal><Reveal delay="motion-delay-2"><article className="rounded-[1.5rem] border border-forest/10 bg-cream p-7"><UsersRound size={23} className="text-gold-dark" /><h2 className="mt-7 font-display text-3xl text-ink">Family involvement is optional.</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">A member may invite a trusted parent or wali for a scoped purpose, can change their mind, and never shares private conversations automatically.</p><Link href="/family-circle" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-forest">Learn about Family Circle <ArrowRight size={16} /></Link></article></Reveal></div></section>

      <section className="bg-cream py-16 md:py-24"><div className="container grid gap-7 lg:grid-cols-[1.05fr_.95fr]"><Reveal><div><p className="eyebrow text-gold-dark">A community across borders</p><h2 className="section-title mt-4">Rooted in home. Open to the diaspora.</h2><p className="mt-5 max-w-xl leading-7 text-muted-foreground">Bantabato currently presents its member journey for people connected to The Gambia, Senegal, and the diaspora. Country choices support reciprocal discovery eligibility; they do not create a popularity ranking or reveal precise location.</p><div className="mt-7 flex flex-wrap gap-3">{["The Gambia", "Senegal", "Diaspora"].map(place => <span key={place} className="inline-flex items-center gap-2 rounded-full border border-forest/10 bg-white px-4 py-2 text-sm font-medium text-forest"><Globe2 size={15} />{place}</span>)}</div></div></Reveal><Reveal delay="motion-delay-1"><aside className="rounded-[1.75rem] border border-forest/10 bg-white p-7 shadow-[0_14px_40px_rgba(21,58,45,.06)]"><UserRoundCheck className="text-gold-dark" size={25} /><h2 className="mt-6 font-display text-3xl text-ink">Membership without pressure.</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">Free membership supports the core considered journey. Premium, where currently effective, can add policy-defined conveniences but cannot bypass matching, safety, verification, privacy, eligibility, consent, or communication authorization.</p><Link href="/membership" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-forest">Review membership facts <ArrowRight size={16} /></Link></aside></Reveal></div></section>

      <section className="pb-16 md:pb-24"><div className="container"><div className="cta-panel"><div><p className="eyebrow text-gold">For Gambians, wherever life has taken you</p><h2 className="mt-4 font-display text-4xl text-cream md:text-5xl">Your next chapter deserves care.</h2><p className="mt-5 max-w-xl text-cream/68">Create a private profile, follow the readiness steps, and move toward a meaningful connection at your own pace.</p></div><div className="flex flex-col gap-3 sm:items-end"><Button asChild size="lg" className="btn-gold shrink-0"><Link href="/register">Create your profile <ArrowRight size={17} /></Link></Button><Link href="/faq" className="inline-flex items-center gap-2 text-sm font-semibold text-cream/85 hover:text-cream"><MessageCircleHeart size={16} />Questions before you start?</Link></div></div></div></section>
    </main>
  </PublicLayout>;
}
