import { MemberShell } from "@/components/MemberShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { StatePanel, StateSkeleton } from "@/components/StatePanel";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, Globe2, Languages, MapPin, Phone, ShieldCheck, WalletCards } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { Link } from "wouter";

type Visibility = "eligible_members" | "matches_only" | "family_circle" | "hidden";
type Detail = "country" | "region" | "city";
type Diaspora = "living_in_gambia" | "living_outside_gambia" | "gambian_diaspora" | "international_member";
type LongDistance = "open" | "prefer_nearby" | "no_preference";

const availabilityLabel: Record<string, string> = { available: "Available", unavailable: "Unavailable", coming_soon: "Coming soon", requires_configuration: "Requires configuration" };
const statusTone = (status: string) => status === "available" ? "bg-emerald-50 text-emerald-700 border-emerald-200" : status === "coming_soon" ? "bg-gold/15 text-gold-dark border-gold/30" : "bg-forest/5 text-muted-foreground border-forest/10";

export default function InternationalPage() {
  const settings = trpc.international.settings.useQuery();
  const save = trpc.international.saveSettings.useMutation({ onSuccess: () => { void settings.refetch(); toast.success("International settings saved securely."); }, onError: () => toast.error("International settings could not be saved. Please try again.") });
  const [residenceCountryId, setResidenceCountryId] = useState(0); const [timezone, setTimezone] = useState("Africa/Banjul"); const [locale, setLocale] = useState("en");
  const [region, setRegion] = useState(""); const [city, setCity] = useState(""); const [visibility, setVisibility] = useState<Visibility>("eligible_members"); const [detail, setDetail] = useState<Detail>("country");
  const [diaspora, setDiaspora] = useState<Diaspora>("living_in_gambia"); const [phone, setPhone] = useState(""); const [phoneCountryId, setPhoneCountryId] = useState<number | null>(null); const [longDistance, setLongDistance] = useState<LongDistance>("no_preference");
  const [origins, setOrigins] = useState<number[]>([]); const [preferred, setPreferred] = useState<number[]>([]); const [futureCountries, setFutureCountries] = useState<number[]>([]); const [futureOptions, setFutureOptions] = useState<string[]>(["open_to_discussion"]);
  useEffect(() => { const data = settings.data; if (!data || data.needsProfile) return; setResidenceCountryId(data.profile.residenceCountryId ?? data.countries.find(country => country.iso2 === "GM")?.id ?? 0); setTimezone(data.profile.timezone); setLocale(data.profile.interfaceLocale); setRegion(data.profile.region ?? ""); setCity(data.profile.city ?? ""); setVisibility(data.profile.locationVisibility); setDetail(data.profile.locationDetailLevel); setDiaspora(data.settings.diasporaStatus); setPhone(data.settings.normalizedPhone ?? ""); setPhoneCountryId(data.settings.phoneCountryId); setLongDistance(data.preferences.longDistancePreference); setFutureOptions((data.preferences.futureResidenceOptions as string[]) || ["open_to_discussion"]); setOrigins(data.origins.map(country => country.id)); setPreferred(data.preferredCountries.filter(country => country.preferencePurpose === "discovery").map(country => country.id)); setFutureCountries(data.preferredCountries.filter(country => country.preferencePurpose === "future_residence").map(country => country.id)); }, [settings.data]);
  const countries = settings.data?.countries ?? []; const activeCountries = countries.filter(country => country.availability.signup === "available"); const selectableLocales = settings.data?.locales ?? [];
  const toggle = (ids: number[], setIds: (ids: number[]) => void, id: number) => setIds(ids.includes(id) ? ids.filter(item => item !== id) : [...ids, id]);
  const toggleOption = (option: string) => setFutureOptions(options => options.includes(option) ? options.filter(item => item !== option) : [...options, option]);
  const submit = () => { if (!residenceCountryId) return toast.error("Choose your country of residence."); save.mutate({ residenceCountryId, region: region || null, city: city || null, timezone, interfaceLocale: locale, locationVisibility: visibility, locationDetailLevel: detail, diasporaStatus: diaspora, phone: phone || null, phoneCountryId, originCountryIds: origins, preferredDiscoveryCountryIds: preferred, futureResidenceCountryIds: futureCountries, futureResidenceOptions: futureOptions as Array<"the_gambia" | "senegal" | "my_current_country" | "partners_country" | "another_country" | "open_to_discussion">, longDistancePreference: longDistance }); };
  if (settings.isLoading) return <MemberShell eyebrow="International access" title="International settings"><StateSkeleton label="Loading your international settings…" /></MemberShell>;
  if (settings.isError || !settings.data) return <MemberShell eyebrow="International access" title="International settings"><StatePanel kind="error" title="International settings are unavailable right now." description="No country, location, language, phone, or cross-border preference has been changed. Please try again." action={<Button onClick={() => settings.refetch()} className="btn-forest">Try again</Button>} /></MemberShell>;
  if (settings.data.needsProfile) return <MemberShell eyebrow="International access" title="International settings" description="Complete your core profile first, then return to add any voluntary diaspora and cross-border preferences."><section className="surface-card max-w-2xl"><Globe2 className="text-gold-dark" size={24} /><h2 className="mt-4 font-display text-3xl text-ink">Start with your core profile.</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">International settings build on your marriage intentions and core profile privacy controls. They do not replace onboarding or create a separate profile.</p><Link href="/app/onboarding" className="btn-forest mt-6 inline-flex">Complete your profile</Link></section></MemberShell>;
  return <MemberShell eyebrow="Diaspora & cross-border" title="International settings" description="Bantabato remains Gambian at its heart. These voluntary details help you state practical, marriage-focused preferences without exposing your address, private phone number, travel patterns, or immigration intentions.">
    <div className="grid gap-6 xl:grid-cols-[1.35fr_.65fr]">
      <form onSubmit={event => { event.preventDefault(); submit(); }} className="space-y-6">
        <section className="surface-card"><div className="flex items-start gap-3"><div className="icon-plate"><MapPin size={19} /></div><div><p className="eyebrow text-gold-dark">Location & privacy</p><h2 className="mt-1 font-display text-3xl text-ink">Share only the level that feels right.</h2></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Country of residence"><Select value={String(residenceCountryId)} onValueChange={value => { setResidenceCountryId(Number(value)); if (!phoneCountryId) setPhoneCountryId(Number(value)); }}><SelectTrigger><SelectValue placeholder="Choose a country" /></SelectTrigger><SelectContent>{activeCountries.map(country => <SelectItem key={country.id} value={String(country.id)}>{country.displayName}</SelectItem>)}</SelectContent></Select></Field><Field label="Time zone"><Input value={timezone} onChange={event => setTimezone(event.target.value)} placeholder="e.g. Africa/Banjul" /></Field><Field label="Region or state (optional)"><Input value={region} onChange={event => setRegion(event.target.value)} /></Field><Field label="City (optional)"><Input value={city} onChange={event => setCity(event.target.value)} /></Field><Field label="Who may see your location"><Select value={visibility} onValueChange={value => setVisibility(value as Visibility)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="eligible_members">Eligible members</SelectItem><SelectItem value="matches_only">Mutual matches only</SelectItem><SelectItem value="family_circle">Family Circle only</SelectItem><SelectItem value="hidden">Hidden</SelectItem></SelectContent></Select></Field><Field label="Location detail"><Select value={detail} onValueChange={value => setDetail(value as Detail)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="country">Country only</SelectItem><SelectItem value="region">Country and region</SelectItem><SelectItem value="city">Country and city</SelectItem></SelectContent></Select></Field></div><p className="mt-4 text-sm leading-6 text-muted-foreground">Exact addresses, GPS data, IP-derived locations, and travel patterns are never displayed to other members.</p></section>
        <section className="surface-card"><div className="flex items-start gap-3"><div className="icon-plate"><Globe2 size={19} /></div><div><p className="eyebrow text-gold-dark">Diaspora context</p><h2 className="mt-1 font-display text-3xl text-ink">Practical context, never a ranking.</h2></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="How you describe your context"><Select value={diaspora} onValueChange={value => setDiaspora(value as Diaspora)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="living_in_gambia">Living in The Gambia</SelectItem><SelectItem value="living_outside_gambia">Living outside The Gambia</SelectItem><SelectItem value="gambian_diaspora">Gambian diaspora</SelectItem><SelectItem value="international_member">International member</SelectItem></SelectContent></Select></Field><Field label="Long-distance preference"><Select value={longDistance} onValueChange={value => setLongDistance(value as LongDistance)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="open">Open to long-distance</SelectItem><SelectItem value="prefer_nearby">Prefer nearby</SelectItem><SelectItem value="no_preference">No preference</SelectItem></SelectContent></Select></Field></div><CountryChecklist title="Countries of origin" note="Private by default. You may select more than one." countries={activeCountries} selected={origins} toggle={id => toggle(origins, setOrigins, id)} /><CountryChecklist title="Countries you would consider for discovery" note="Only an explicit, logistical preference. It never changes anyone’s value or safety treatment." countries={activeCountries} selected={preferred} toggle={id => toggle(preferred, setPreferred, id)} /><CountryChecklist title="Countries you would consider living in after marriage" note="This is an invitation to discuss, not an immigration or relocation promise." countries={activeCountries} selected={futureCountries} toggle={id => toggle(futureCountries, setFutureCountries, id)} /><div className="mt-6"><p className="text-sm font-semibold text-ink">Future-home approach</p><div className="mt-3 flex flex-wrap gap-2">{[["the_gambia","The Gambia"],["senegal","Senegal"],["my_current_country","My current country"],["partners_country","Partner’s country"],["another_country","Another country"],["open_to_discussion","Open to discussion"]].map(([key,label]) => <button key={key} type="button" onClick={() => toggleOption(key)} className={`rounded-full border px-3 py-2 text-xs font-semibold ${futureOptions.includes(key) ? "border-gold bg-gold/15 text-gold-dark" : "border-forest/10 bg-white text-muted-foreground"}`}>{label}</button>)}</div></div></section>
        <section className="surface-card"><div className="flex items-start gap-3"><div className="icon-plate"><Languages size={19} /></div><div><p className="eyebrow text-gold-dark">Language & private contact</p><h2 className="mt-1 font-display text-3xl text-ink">Prepared, never assumed.</h2></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Account language"><Select value={locale} onValueChange={setLocale}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{selectableLocales.map(item => <SelectItem key={item.code} value={item.code}>{item.displayName} · {item.status === "available" ? "Available" : "Coming soon"}</SelectItem>)}</SelectContent></Select></Field><Field label="Private phone country"><Select value={phoneCountryId ? String(phoneCountryId) : "none"} onValueChange={value => setPhoneCountryId(value === "none" ? null : Number(value))}><SelectTrigger><SelectValue placeholder="No phone saved" /></SelectTrigger><SelectContent><SelectItem value="none">No phone saved</SelectItem>{activeCountries.map(country => <SelectItem key={country.id} value={String(country.id)}>{country.displayName}</SelectItem>)}</SelectContent></Select></Field><Field label="Private phone number"><Input value={phone} onChange={event => setPhone(event.target.value)} placeholder="Saved privately; SMS may be unavailable" /></Field></div><p className="mt-4 text-sm leading-6 text-muted-foreground">Phone numbers are normalized by the selected country, stored privately, and are never shown in discovery, profiles, Family Circle, or member messaging. SMS verification is explicitly unavailable until a provider is configured.</p></section>
        <Button type="submit" className="w-full btn-forest" disabled={save.isPending}>{save.isPending ? "Saving securely…" : "Save international settings"}</Button>
      </form>
      <aside className="space-y-5"><section className="welcome-panel min-h-0"><ShieldCheck className="text-gold" size={24} /><p className="mt-5 text-xs font-semibold uppercase tracking-[.16em] text-gold">Marriage-first abroad</p><h2 className="mt-2 font-display text-3xl text-cream">The world is welcome. Matrimony remains the purpose.</h2><p className="mt-4 text-sm leading-6" style={{ color: "#fcf8ef" }}>International access does not offer visas, immigration advice, country prestige, automatic translation, live exchange rates, or special safety treatment.</p></section><section className="surface-card"><p className="eyebrow text-gold-dark">Country readiness</p><h2 className="mt-2 font-display text-2xl text-ink">Clear about what works where.</h2><div className="mt-5 space-y-4">{countries.map(country => <div key={country.id} className="rounded-2xl border border-forest/10 bg-white p-4"><div className="flex items-center justify-between gap-3"><p className="font-semibold text-ink">{country.displayName}</p><Badge className={`border ${statusTone(country.availability.signup)}`}>{availabilityLabel[country.availability.signup]}</Badge></div><p className="mt-2 text-xs leading-5 text-muted-foreground">Discovery: {availabilityLabel[country.availability.discovery]} · Verification: {availabilityLabel[country.availability.verification]} · Payment: {availabilityLabel[country.availability.payment]}</p></div>)}</div></section><section className="surface-card"><WalletCards className="text-gold-dark" size={22} /><h2 className="mt-4 font-display text-2xl text-ink">No false payment promise.</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Currency metadata supports clear display. It does not imply a live payment provider or exchange-rate conversion.</p></section></aside>
    </div>
  </MemberShell>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-2"><Label>{label}</Label>{children}</label>; }
function CountryChecklist({ title, note, countries, selected, toggle }: { title: string; note: string; countries: Array<{ id: number; displayName: string }>; selected: number[]; toggle: (id: number) => void }) { return <div className="mt-6"><p className="text-sm font-semibold text-ink">{title}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{note}</p><div className="mt-3 flex flex-wrap gap-2">{countries.map(country => <button type="button" key={country.id} onClick={() => toggle(country.id)} className={`inline-flex items-center gap-2 rounded-full border px-3 py-2 text-xs font-semibold ${selected.includes(country.id) ? "border-gold bg-gold/15 text-gold-dark" : "border-forest/10 bg-white text-muted-foreground"}`}>{selected.includes(country.id) ? <CheckCircle2 size={14} /> : null}{country.displayName}</button>)}</div></div>; }
