import { MemberShell } from "@/components/MemberShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { StatePanel, StateSkeleton } from "@/components/StatePanel";
import { useNetworkState } from "@/hooks/useDeviceExperience";
import { clearSafeDraft, draftKey, loadSafeDraft, saveSafeDraft } from "@/lib/mobileExperience";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";
import { CircleAlert, HeartHandshake, ImageOff, LockKeyhole, MessageCircle, Mic, PauseCircle, PhoneCall, PlayCircle, Send, ShieldAlert, ShieldCheck, Square, Video, Volume2 } from "lucide-react";
import React, { useEffect, useRef, useState } from "react";
import { useLocation } from "wouter";

export function MemberProfileDetailPage({ profileId }: { profileId: number }) {
  const profile = trpc.profile.view.useQuery({ profileId });
  const compatibility = trpc.compatibility.explain.useQuery({ profileId }, { enabled: Boolean(profile.data) });
  const utils = trpc.useUtils();
  const [note, setNote] = useState("");
  const [, setLocation] = useLocation();
  const sendInterest = trpc.interests.send.useMutation({ onSuccess: () => setLocation("/app/matches") });
  const report = trpc.safety.report.useMutation({ onSuccess: () => toast.success("Your report was submitted privately. Our Trust & Safety team will review it.") });
  const block = trpc.safety.block.useMutation({ onSuccess: () => { utils.discovery.list.invalidate(); toast.success("This member has been blocked. Further contact is stopped."); setLocation("/app/discover"); } });
  const member = profile.data;

  return <MemberShell eyebrow="Member profile" title={member?.displayName || "Considered profile"} description="Review the details a member has chosen to share. You control whether to send an introduction request.">
    {profile.isLoading ? <StateSkeleton label="Preparing this considered profile…" /> : profile.isError ? <StatePanel kind="error" title="This profile is unavailable right now." description="No profile details have been shown. Please try again." action={<Button onClick={() => profile.refetch()} className="btn-forest">Try again</Button>} /> : !member ? <div className="empty-state"><ShieldAlert size={25} /><h2 className="mt-6 font-display text-3xl">This profile is unavailable.</h2><p className="mt-3 text-sm text-muted-foreground">The member may be hidden, paused, or no longer eligible for discovery.</p></div> : <div className="grid gap-7 xl:grid-cols-[1.1fr_.9fr]">
      <section className="surface-card">
        <div className="profile-photo-placeholder"><ImageOff size={26} /><span>{member.hasMutualMatch ? "Photos may be shown according to the member’s settings" : "Photos remain private until a mutual match"}</span></div>
        <div className="mt-7 flex flex-wrap gap-2">{member.identityVerified ? <Badge className="badge-quiet"><ShieldCheck size={13} /> Identity reviewed</Badge> : null}{[member.religion, member.practiceLevel, member.educationLevel, member.profession, member.tribe].filter(Boolean).map(tag => <Badge key={tag} variant="outline" className="border-forest/15 bg-cream text-forest">{tag}</Badge>)}</div>
        <h2 className="mt-7 font-display text-3xl text-ink">About this member</h2>
        <p className="mt-3 leading-7 text-muted-foreground">{member.about || "This member has chosen not to add a written introduction yet."}</p>
        <div className="mt-7 grid gap-4 border-t border-forest/10 pt-7 sm:grid-cols-2"><Detail label="Location" value={[member.city, member.country].filter(Boolean).join(", ") || (member.residenceType === "gambia" ? "The Gambia" : "Gambian diaspora")} /><Detail label="Marriage timeline" value={member.marriageTimeline || "To be discussed"} /><Detail label="Marriage intention" value={member.marriageIntent || "To be discussed"} /><Detail label="Relocation" value={member.relocationWillingness?.replace(/_/g, " ") || "To be discussed"} /><Detail label="Family approach" value={member.familyInvolvementPreference?.replace(/_/g, " ") || "Private"} /><Detail label="Family background" value={member.familyBackground || "Private until a permitted connection is established"} /></div>
        <div className="mt-7 grid gap-4 border-t border-forest/10 pt-7 sm:grid-cols-2"><ProfileSection title="Values" text={member.values || member.importantPrinciples} empty="This member has not shared additional values here." /><ProfileSection title="Lifestyle" text={member.lifestyle} empty="Lifestyle details are private or not yet shared." /><ProfileSection title="Education & career" text={[member.educationField || member.educationLevel, member.profession, member.industry].filter(Boolean).join(" · ")} empty="Education and career details are private or not yet shared." /><ProfileSection title="Interests" text={[...(Array.isArray(member.interests) ? member.interests : []), ...(Array.isArray(member.hobbies) ? member.hobbies : [])].join(" · ")} empty="Interests are private or not yet shared." /></div>
      </section>
      <aside className="space-y-5">
        <section className="surface-card"><div className="icon-plate"><HeartHandshake size={20} /></div><h2 className="mt-6 font-display text-3xl">Compatibility, explained.</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">Bantabato presents respectful alignment signals and considerations—not a percentage or a judgment.</p><div className="mt-5 space-y-3">{compatibility.data?.compatible.slice(0, 3).map(item => <p key={`${item.dimension}-${item.explanation}`} className="rounded-xl bg-forest/5 p-3 text-xs leading-5 text-forest">{item.explanation}</p>)}{compatibility.data?.considerations.slice(0, 2).map(item => <p key={`${item.dimension}-${item.explanation}`} className="rounded-xl bg-gold/10 p-3 text-xs leading-5 text-ink">Potential consideration: {item.explanation}</p>)}{!compatibility.isLoading && !compatibility.data?.compatible.length && !compatibility.data?.considerations.length ? <p className="text-sm leading-6 text-muted-foreground">Complete your compatibility preferences to receive clearer, explainable discovery signals.</p> : null}</div></section>
        <section className="surface-card"><div className="icon-plate"><HeartHandshake size={20} /></div><h2 className="mt-6 font-display text-3xl">Send an introduction.</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">A respectful note is optional. Messaging stays unavailable unless this member accepts the request and a mutual match is created.</p><Textarea value={note} onChange={event => setNote(event.target.value)} maxLength={500} className="mt-5 min-h-28 bg-cream/50" placeholder="A brief, considerate introduction (optional)" /><Button onClick={() => sendInterest.mutate({ recipientProfileId: profileId, message: note || undefined })} disabled={sendInterest.isPending} className="mt-4 w-full btn-forest">{sendInterest.isPending ? "Sending…" : "Send introduction request"} <Send size={16} /></Button></section>
        <section className="surface-card"><div className="flex gap-3"><LockKeyhole className="shrink-0 text-gold-dark" size={19} /><div><p className="text-sm font-semibold text-ink">Privacy respected</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Protected photos and family details are never force-revealed by an interest request.</p></div></div></section>
        <section className="surface-card"><p className="text-sm font-semibold text-ink">Safety controls</p><p className="mt-2 text-xs leading-5 text-muted-foreground">You can remove this profile from your experience or flag a concern for the Trust & Safety team.</p><div className="mt-4 flex flex-wrap gap-3"><Button onClick={() => report.mutate({ reportedProfileId: profileId, reason: "other" })} variant="outline" size="sm"><CircleAlert size={15} /> Report</Button><Button onClick={() => block.mutate({ blockedProfileId: profileId })} variant="outline" size="sm" className="text-destructive hover:text-destructive"><ShieldAlert size={15} /> Block</Button></div></section>
      </aside>
    </div>}
  </MemberShell>;
}

export function MessageThreadPage({ conversationId }: { conversationId: number }) {
  const messages = trpc.messaging.messages.useQuery({ conversationId });
  const conversations = trpc.messaging.conversations.useQuery();
  const prompts = trpc.messaging.prompts.useQuery({ conversationId });
  const readiness = trpc.readiness.status.useQuery({ conversationId });
  const utils = trpc.useUtils();
	  const [body, setBody] = useState("");
	  const [voiceDraft, setVoiceDraft] = useState<{ dataUrl: string; durationSeconds: number } | null>(null);
	  const messageDraftKey = draftKey("message", String(conversationId));
	  useEffect(() => { setBody(loadSafeDraft<string>(messageDraftKey) ?? ""); }, [messageDraftKey]);
	  const updateBody = (value: string) => { setBody(value); if (value.trim()) saveSafeDraft(messageDraftKey, value); else clearSafeDraft(messageDraftKey); };
	  const send = trpc.messaging.sendText.useMutation({ onSuccess: () => { setBody(""); clearSafeDraft(messageDraftKey); utils.messaging.messages.invalidate({ conversationId }); utils.messaging.conversations.invalidate(); }, onError: () => toast.error("We couldn’t send that message. Your draft is still saved on this device; check your connection and retry.") });
	  const uploadVoice = trpc.messaging.uploadVoice.useMutation({ onSuccess: () => { setVoiceDraft(null); utils.messaging.messages.invalidate({ conversationId }); utils.messaging.conversations.invalidate(); toast.success("Your private voice note was sent."); }, onError: () => toast.error("We couldn’t send that voice note. Keep this page open and retry when your connection returns.") });
  const report = trpc.safety.report.useMutation({ onSuccess: () => toast.success("Your report was submitted privately. Our Trust & Safety team will review it.") });
  const profile = trpc.profile.mine.useQuery();
  const network = useNetworkState();
  const block = trpc.messaging.block.useMutation({ onSuccess: () => toast.success("This member has been blocked. Further contact is stopped.") });
  const preference = trpc.messaging.preferences.useMutation({ onSuccess: () => toast.success("Conversation preference saved.") });
  const changeState = trpc.messaging.setState.useMutation({ onSuccess: () => { utils.messaging.messages.invalidate({ conversationId }); toast.success("Conversation updated."); } });
  const grantConsent = trpc.readiness.grantConsent.useMutation({ onSuccess: () => { utils.readiness.status.invalidate({ conversationId }); toast.success("Your communication preference has been saved."); }, onError: error => toast.error(error.message) });
  const withdrawConsent = trpc.readiness.withdrawConsent.useMutation({ onSuccess: () => { utils.readiness.status.invalidate({ conversationId }); toast.success("Your consent was withdrawn and the capability is no longer available."); }, onError: error => toast.error(error.message) });
  const conversation = conversations.data?.items.find(item => item.id === conversationId);
  const otherProfileId = messages.data?.conversation?.otherProfileId;

  return <MemberShell eyebrow="Private conversation" title={conversation?.otherProfile?.displayName || "Your mutual match"} description="A respectful space available because both members chose to connect.">
    <section className="surface-card overflow-hidden p-0">
      <div className="flex flex-wrap items-center justify-between gap-4 border-b border-forest/10 px-5 py-5"><div className="flex items-center gap-3"><div className="icon-plate"><MessageCircle size={18} /></div><div><p className="text-sm font-semibold text-ink">Private mutual interest</p><p className="mt-1 text-xs text-muted-foreground">Contact details remain private; you may pause, report, or block at any time.</p></div></div><div className="flex flex-wrap gap-1"><Button onClick={() => preference.mutate({ conversationId, isMuted: true })} variant="ghost" size="sm">Mute</Button><Button onClick={() => changeState.mutate({ conversationId, state: "paused" })} variant="ghost" size="sm">Pause</Button><Button onClick={() => report.mutate({ conversationId, reason: "other" })} variant="ghost" size="sm" className="text-muted-foreground"><CircleAlert size={15} /> Report</Button>{otherProfileId ? <Button onClick={() => block.mutate({ conversationId })} variant="ghost" size="sm" className="text-destructive hover:text-destructive"><ShieldAlert size={15} /> Block</Button> : null}</div></div>
      <div className="border-b border-forest/10 bg-cream/50 px-5 py-4"><p className="text-sm font-semibold text-ink">{prompts.data?.introduction || "You both expressed interest in getting to know each other for marriage."}</p><div className="mt-3 flex flex-wrap gap-2">{prompts.data?.prompts.slice(0, 3).map(prompt => <Button key={prompt} variant="outline" size="sm" onClick={() => setBody(prompt)} className="h-auto whitespace-normal text-left text-xs">{prompt}</Button>)}</div></div>
      <ReadinessPanel readiness={readiness.data} loading={readiness.isLoading} unavailable={readiness.isError} pending={grantConsent.isPending || withdrawConsent.isPending} onGrant={capability => grantConsent.mutate({ conversationId, capability })} onWithdraw={capability => withdrawConsent.mutate({ conversationId, capability })} />
      <div className="message-thread">{messages.isLoading ? <StateSkeleton label="Loading your private conversation…" /> : messages.isError ? <StatePanel kind="error" title="This conversation is unavailable right now." description="No messages have been shown. Please try again." action={<Button onClick={() => messages.refetch()} className="btn-forest">Try again</Button>} /> : messages.data?.items.length ? messages.data.items.map(message => <MessageItem key={message.id} message={message} conversationId={conversationId} isOwner={message.senderProfileId === profile.data?.id} />) : <div className="py-10 text-center"><ShieldCheck className="mx-auto text-gold-dark" size={24} /><p className="mt-4 font-display text-2xl text-ink">Begin with courtesy.</p><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-muted-foreground">This conversation opened only after mutual interest. Use an optional prompt, a short message, or a voice note when it helps you communicate clearly.</p></div>}</div>
      <form onSubmit={event => { event.preventDefault(); if (!body.trim()) return; if (network === "offline") { toast.error("You appear to be offline. Your message draft is saved on this device; reconnect before sending."); return; } send.mutate({ conversationId, body: body.trim() }); }} className="border-t border-forest/10 bg-cream/50 p-4"><div className="flex items-end gap-3"><Textarea value={body} onChange={event => updateBody(event.target.value)} maxLength={2000} aria-label="Private text message" className="min-h-[52px] resize-none bg-white" placeholder="Write a respectful message…" /><Button type="submit" aria-label="Send message" disabled={send.isPending || !body.trim() || network === "offline"} className="btn-forest self-end"><Send size={16} /></Button></div>{network === "offline" ? <p className="member-composer-status" role="status">You’re offline. Your text draft stays on this device; reconnect before sending.</p> : null}<VoiceComposer disabled={uploadVoice.isPending || network === "offline"} disabledReason={network === "offline" ? "Reconnect before recording or sending a voice note." : uploadVoice.isPending ? "Your private voice note is being sent." : undefined} sending={uploadVoice.isPending} errorMessage={uploadVoice.isError ? "Not sent yet — retry when you are ready." : undefined} draft={voiceDraft} onDraft={setVoiceDraft} onSend={draft => uploadVoice.mutate({ conversationId, ...draft })} /><p className="mt-3 text-xs leading-5 text-muted-foreground">Text drafts are saved only on this device until sent or discarded. Voice notes stay in this private conversation and are limited to three minutes for mobile-friendly upload.</p></form>
    </section>
  </MemberShell>;
}

export function ReadinessPanel({ readiness, loading, unavailable, pending, onGrant, onWithdraw }: { readiness: { stage: string; status: string; readyForReview: boolean; reviewRequired: boolean; explanation: string; criteria: Array<{ label: string; met: boolean }>; yourConsents: Array<{ capability: "voice" | "video"; status: "pending" | "granted" | "withdrawn" | "declined" }>; partnerConsentReceived: Array<{ capability: "voice" | "video"; granted: boolean }>; permissions: Array<{ capability: "voice" | "video"; status: "unavailable" | "available" | "paused" | "revoked"; providerConfigured: boolean }>; safetyGuidance: string[]; futureProvider: { configured: boolean; message: string } } | undefined; loading: boolean; unavailable: boolean; pending: boolean; onGrant: (capability: "voice" | "video") => void; onWithdraw: (capability: "voice" | "video") => void }) {
  if (loading) return <div className="border-b border-forest/10 px-5 py-5"><div className="h-20 animate-pulse rounded-2xl bg-forest/8" /></div>;
  if (!readiness) return <div className="border-b border-forest/10 bg-cream/35 px-5 py-4"><p className="text-sm font-semibold text-ink">Connection readiness is private to an active mutual match.</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{unavailable ? "This conversation is unavailable, paused beyond the current access rules, or no longer active." : "It will appear here once this mutual conversation is available."}</p></div>;
  const consent = (capability: "voice" | "video") => readiness.yourConsents.find(item => item.capability === capability)?.status;
  const permission = (capability: "voice" | "video") => readiness.permissions.find(item => item.capability === capability)?.status;
  const ConsentButton = ({ capability, icon: Icon, label }: { capability: "voice" | "video"; icon: typeof PhoneCall; label: string }) => { const granted = consent(capability) === "granted"; const available = permission(capability) === "available"; return <div className="rounded-xl border border-forest/10 bg-white p-3"><div className="flex items-start justify-between gap-3"><div><p className="flex items-center gap-2 text-sm font-semibold text-ink"><Icon size={15} /> {label}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{available ? "Available when a future privacy-preserving calling provider is connected." : granted ? "Your consent is recorded. The other member’s separate choice and current safeguards still apply." : readiness.readyForReview ? "Choose this only if you are comfortable considering this next step. Both members must agree." : "This choice becomes available after the current mutual-readiness requirements are met."}</p></div><Badge variant="outline" className="border-forest/15 bg-cream text-forest">{available ? "Available" : granted ? "Consent recorded" : "Not enabled"}</Badge></div>{granted ? <Button type="button" onClick={() => onWithdraw(capability)} disabled={pending} variant="outline" size="sm" className="mt-3">Withdraw consent</Button> : <Button type="button" onClick={() => onGrant(capability)} disabled={pending || !readiness.readyForReview} variant="outline" size="sm" className="mt-3">Enable {label}</Button>}</div>; };
  return <section className="border-b border-forest/10 bg-white px-5 py-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow text-gold-dark">Connection readiness</p><h2 className="mt-1 font-display text-2xl text-ink">A shared next step, never an automatic one.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{readiness.explanation}</p></div><Badge className="badge-quiet">{readiness.status.replace(/_/g, " ")}</Badge></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{readiness.criteria.slice(0, 6).map(item => <p key={item.label} className="flex items-center gap-2 rounded-xl bg-cream/60 px-3 py-2 text-xs text-ink">{item.met ? <ShieldCheck className="shrink-0 text-forest" size={15} /> : <LockKeyhole className="shrink-0 text-gold-dark" size={14} />}{item.label}</p>)}</div><div className="mt-4 grid gap-3 lg:grid-cols-2"><ConsentButton capability="voice" icon={PhoneCall} label="Voice communication" /><ConsentButton capability="video" icon={Video} label="Video communication" /></div><div className="mt-4 rounded-xl bg-forest/5 p-3"><p className="text-xs font-semibold text-ink">Before any future call</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{readiness.futureProvider.message}</p><ul className="mt-2 grid gap-1 text-xs leading-5 text-muted-foreground sm:grid-cols-2">{readiness.safetyGuidance.map(item => <li key={item}>• {item}</li>)}</ul></div></section>;
}

function VoiceComposer({ disabled, disabledReason, sending, errorMessage, draft, onDraft, onSend }: { disabled: boolean; disabledReason?: string; sending: boolean; errorMessage?: string; draft: { dataUrl: string; durationSeconds: number } | null; onDraft: (draft: { dataUrl: string; durationSeconds: number } | null) => void; onSend: (draft: { dataUrl: string; durationSeconds: number }) => void }) {
  const [recording, setRecording] = useState(false); const [paused, setPaused] = useState(false); const [seconds, setSeconds] = useState(0); const [captureError, setCaptureError] = useState(""); const recorder = useRef<MediaRecorder | null>(null); const chunks = useRef<BlobPart[]>([]); const startedAt = useRef(0); const pausedMs = useRef(0); const pausedAt = useRef(0); const timer = useRef<number | null>(null); const discarded = useRef(false);
  const stopTimer = () => { if (timer.current) { window.clearInterval(timer.current); timer.current = null; } };
  const begin = async () => { if (disabled) return; setCaptureError(""); if (!navigator.mediaDevices?.getUserMedia || typeof MediaRecorder === "undefined") { setCaptureError("Voice recording is not supported in this browser. You can still send a text message."); return; } try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); const item = new MediaRecorder(stream); chunks.current = []; discarded.current = false; pausedMs.current = 0; startedAt.current = Date.now(); item.ondataavailable = event => { if (event.data.size) chunks.current.push(event.data); }; item.onstop = () => { stopTimer(); const durationSeconds = Math.max(1, Math.ceil((Date.now() - startedAt.current - pausedMs.current) / 1000)); const blob = new Blob(chunks.current, { type: item.mimeType || "audio/webm" }); if (!discarded.current) { const reader = new FileReader(); reader.onload = () => { if (typeof reader.result === "string") onDraft({ dataUrl: reader.result, durationSeconds }); }; reader.readAsDataURL(blob); } stream.getTracks().forEach(track => track.stop()); setRecording(false); setPaused(false); setSeconds(0); }; recorder.current = item; item.start(); setRecording(true); timer.current = window.setInterval(() => { const elapsed = Math.floor((Date.now() - startedAt.current - pausedMs.current) / 1000); setSeconds(elapsed); if (elapsed >= 180) item.stop(); }, 500); } catch (error) { const name = error instanceof DOMException ? error.name : ""; setCaptureError(name === "NotAllowedError" ? "Microphone access was not granted. Allow it in your browser settings, or send a text message instead." : "We couldn’t start recording. Check microphone access and try again."); } };
  const finish = () => recorder.current?.state !== "inactive" && recorder.current?.stop(); const togglePause = () => { const item = recorder.current; if (!item) return; if (item.state === "recording") { pausedAt.current = Date.now(); item.pause(); setPaused(true); } else if (item.state === "paused") { pausedMs.current += Date.now() - pausedAt.current; item.resume(); setPaused(false); } }; const cancel = () => { discarded.current = true; finish(); };
  if (draft) return <div className="voice-composer voice-composer-preview"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-xs font-semibold text-ink">Voice-note preview · {draft.durationSeconds}s</p><Badge className="badge-quiet">{sending ? "Sending" : errorMessage ? "Needs retry" : "Ready"}</Badge></div><VoiceWaveform seconds={draft.durationSeconds} paused className="mt-3" /><audio controls controlsList="nodownload" src={draft.dataUrl} className="mt-3 w-full" aria-label="Voice-note preview" />{sending ? <p role="status" className="member-composer-status">Sending your private voice note…</p> : null}{errorMessage ? <p role="status" className="member-composer-status member-composer-status-warning">{errorMessage}</p> : null}<div className="mt-3 flex flex-wrap gap-2"><Button type="button" variant="outline" size="sm" onClick={() => onDraft(null)} disabled={sending}>Delete</Button><Button type="button" size="sm" className="btn-forest" disabled={disabled} onClick={() => onSend(draft)}><Send size={14} /> {sending ? "Sending…" : errorMessage ? "Retry voice note" : "Send voice note"}</Button></div></div>;
  return <div className="voice-composer mt-3">{recording ? <div><div className="flex flex-wrap items-center justify-between gap-3"><div><p role="status" className="text-xs font-semibold text-ink">{paused ? "Voice note paused" : "Recording private voice note"} · {seconds}s of 180s</p><p className="mt-1 text-xs text-muted-foreground">The waveform is visual feedback only. It is never used to rate your activity.</p></div><Badge className="badge-quiet">{paused ? "Paused" : "Recording"}</Badge></div><VoiceWaveform seconds={seconds} paused={paused} className="mt-3" /><div className="mt-3 flex flex-wrap items-center gap-2"><Button type="button" onClick={finish} variant="outline" className="text-destructive"><Square size={16} /> Stop and preview</Button><Button type="button" onClick={togglePause} variant="outline">{paused ? <PlayCircle size={16} /> : <PauseCircle size={16} />}{paused ? "Resume" : "Pause"}</Button><Button type="button" onClick={cancel} variant="ghost">Cancel and delete</Button></div></div> : <div className="flex flex-wrap items-center gap-3"><Button type="button" onClick={begin} disabled={disabled} variant="outline"><Mic size={16} /> Record voice note</Button>{disabledReason ? <p role="status" className="text-xs leading-5 text-muted-foreground">{disabledReason}</p> : null}</div>}{captureError ? <div className="mt-3 flex flex-wrap items-center gap-3 rounded-xl border border-gold/25 bg-gold/5 p-3"><p role="status" className="text-xs leading-5 text-ink">{captureError}</p><Button type="button" size="sm" variant="outline" disabled={disabled} onClick={begin}>Try again</Button></div> : null}</div>;
}

function MessageItem({ message, conversationId, isOwner }: { message: { id: number; senderProfileId: number; messageType: "text" | "voice" | "image"; body: string | null; durationSeconds: number | null; createdAt: Date; deliveryStatus: "sent" | "delivered" | "failed" }; conversationId: number; isOwner: boolean }) { const reportMessage = trpc.messaging.reportMessage.useMutation({ onSuccess: () => toast.success("The message report was sent privately to Trust & Safety.") }); const removeVoice = trpc.messaging.deleteVoice.useMutation(); return <div className={`message-bubble ${isOwner ? "" : "message-bubble-incoming"}`}><div className="flex gap-2"><div className="min-w-0 flex-1">{message.messageType === "voice" ? <VoicePlayer conversationId={conversationId} messageId={message.id} durationSeconds={message.durationSeconds} /> : <p>{message.body}</p>}<span>{new Date(message.createdAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}{isOwner ? ` · ${message.deliveryStatus}` : ""}</span></div><div className="flex shrink-0 flex-col gap-1"><Button variant="ghost" size="icon" className="h-7 w-7" aria-label="Report message" onClick={() => reportMessage.mutate({ conversationId, messageId: message.id, reason: "other" })}><CircleAlert size={14} /></Button>{isOwner && message.messageType === "voice" ? <Button variant="ghost" size="icon" className="h-7 w-7" aria-label="Delete voice note" onClick={() => removeVoice.mutate({ conversationId, messageId: message.id })}><Square size={12} /></Button> : null}</div></div></div>; }
function VoicePlayer({ conversationId, messageId, durationSeconds }: { conversationId: number; messageId: number; durationSeconds: number | null }) { const voice = trpc.messaging.voiceUrl.useQuery({ conversationId, messageId }); const [position, setPosition] = useState(0); const [duration, setDuration] = useState(durationSeconds ?? 0); if (voice.isError) return <div className="rounded-xl bg-white/60 p-3"><p role="status" className="text-xs text-muted-foreground">We couldn’t prepare this private audio. Please try again.</p><Button type="button" size="sm" variant="outline" className="mt-2" onClick={() => voice.refetch()}>Try again</Button></div>; return <div className="voice-player"><div className="flex items-center gap-3"><Volume2 className="text-gold-dark" size={18} />{voice.data?.url ? <audio controls controlsList="nodownload" className="min-w-0 flex-1" onLoadedMetadata={event => setDuration(event.currentTarget.duration || durationSeconds || 0)} onTimeUpdate={event => setPosition(event.currentTarget.currentTime)}><source src={voice.data.url} type={voice.data.mimeType || undefined} /></audio> : <span role="status" className="text-xs text-muted-foreground">Preparing private audio…</span>}<span className="shrink-0 text-xs text-muted-foreground">{durationSeconds ? `${durationSeconds}s` : ""}</span></div>{voice.data?.url ? <div className="mt-2 flex items-center gap-2"><progress aria-label="Voice-note playback progress" value={Math.min(position, duration || 1)} max={duration || 1} className="voice-playback-progress" /><span className="text-[11px] text-muted-foreground">{formatDuration(position)} / {formatDuration(duration)}</span></div> : null}</div>; }
function VoiceWaveform({ seconds, paused, className = "" }: { seconds: number; paused: boolean; className?: string }) { return <div className={`voice-waveform ${paused ? "voice-waveform-paused" : ""} ${className}`} aria-hidden="true">{Array.from({ length: 28 }, (_, index) => <span key={index} style={{ "--voice-bar": `${20 + ((index * 13 + Math.floor(seconds * 7)) % 68)}%` } as React.CSSProperties} />)}</div>; }
function formatDuration(value: number) { const total = Math.max(0, Math.floor(value || 0)); return `${Math.floor(total / 60)}:${String(total % 60).padStart(2, "0")}`; }

function Detail({ label, value }: { label: string; value: string }) { return <div><p className="text-[11px] font-semibold uppercase tracking-[.13em] text-gold-dark">{label}</p><p className="mt-1 text-sm capitalize leading-6 text-ink">{value}</p></div>; }
function ProfileSection({ title, text, empty }: { title: string; text?: string | null; empty: string }) { return <div className="rounded-xl bg-cream/60 p-4"><p className="text-[11px] font-semibold uppercase tracking-[.13em] text-gold-dark">{title}</p><p className="mt-2 text-sm leading-6 text-ink">{text || empty}</p></div>; }
