import { MemberShell } from "@/components/MemberShell";
import { StatePanel, StateSkeleton } from "@/components/StatePanel";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { BellRing, Camera, CheckCircle2, ChevronRight, CircleAlert, Compass, CreditCard, FileCheck2, HeartHandshake, Lightbulb, LockKeyhole, MessageCircle, ShieldCheck, UsersRound } from "lucide-react";
import { Link } from "wouter";

function statusLabel(value?: string | null) { return value ? value.replace(/_/g, " ") : "Not started"; }

export default function MemberDashboardPage() {
  const profile = trpc.profile.mine.useQuery();
  const verification = trpc.verification.summary.useQuery();
  const photos = trpc.uploads.profilePhotos.useQuery();
  const incoming = trpc.interests.incoming.useQuery();
  const matches = trpc.matches.list.useQuery();
  const conversations = trpc.messaging.conversations.useQuery();
  const family = trpc.family.list.useQuery();
  const notifications = trpc.notifications.list.useQuery();
  const billing = trpc.billing.summary.useQuery();
  const safety = trpc.safety.center.useQuery();
  const declaration = trpc.success.mine.useQuery();
  const recommendations = trpc.recommendations.list.useQuery({ limit: 3 }, { enabled: profile.data?.eligibility?.discoveryEligible === true });

  if (profile.isLoading) return <MemberShell eyebrow="Your Bantaba" title="A meaningful start." description="Your command center gathers only the private account status and actions that need your attention."><StateSkeleton label="Loading your protected command center…" /></MemberShell>;
  if (profile.isError) return <MemberShell eyebrow="Your Bantaba" title="A meaningful start." description="Your command center gathers only the private account status and actions that need your attention."><StatePanel kind="error" title="Your command center is unavailable right now." description="No profile, safety, billing, relationship, or notification state has been changed. Please try again." action={<Button className="btn-forest" onClick={() => profile.refetch()}>Try again</Button>} /></MemberShell>;

  const member = profile.data;
  const eligibility = member?.eligibility;
  const latestVerification = verification.data?.find(record => record.verificationType === "identity_document");
  const approvedPhotos = eligibility?.approvedPhotoCount ?? 0;
  const pendingPhotos = member?.completeness?.pendingPhotoCount ?? 0;
  const unreadNotifications = (notifications.data ?? []).filter(item => !item.readAt).length;
  const unreadMessages = (conversations.data?.items ?? []).reduce((sum, item) => sum + (item.unreadCount ?? 0), 0);
  const pendingFamily = (family.data ?? []).filter(link => ["pending", "pending_verification"].includes(link.status)).length;
  const membership = billing.data?.membership;
  const pendingRefund = (billing.data?.refunds ?? []).filter(refund => ["requested", "processing"].includes(refund.status)).length;
  const recommendationCount = recommendations.data?.items.length ?? 0;
  const importantActions = [
    !eligibility?.profileComplete ? { title: eligibility?.title || "Complete your profile foundation", detail: eligibility?.detail || "Finish your profile before discovery can begin.", href: eligibility?.photosRemaining ? "/app/photos" : "/app/onboarding", label: eligibility?.nextAction || "Continue profile" } : null,
    latestVerification?.status !== "approved" ? { title: "Review your verification status", detail: latestVerification ? `Current private status: ${statusLabel(latestVerification.status)}.` : "Identity review has not started.", href: "/app/verification", label: "Open verification" } : null,
    incoming.data?.length ? { title: `${incoming.data.length} introduction${incoming.data.length === 1 ? "" : "s"} awaiting your choice`, detail: "An introduction stays one-sided until you respond. No conversation opens automatically.", href: "/app/matches", label: "Review introductions" } : null,
    unreadMessages ? { title: `${unreadMessages} unread private message${unreadMessages === 1 ? "" : "s"}`, detail: "Messages exist only within an active mutual connection and retain report/block controls.", href: "/app/messages", label: "Open messages" } : null,
    pendingFamily ? { title: `${pendingFamily} Family Circle invitation or verification item`, detail: "A pending Family Circle link grants no private message, document, decision, or call-consent access.", href: "/app/family", label: "Review Family Circle" } : null,
    pendingRefund ? { title: `${pendingRefund} refund request${pendingRefund === 1 ? "" : "s"} pending`, detail: "Finance/provider review is not a completed refund and does not change protections or membership status.", href: "/app/billing", label: "Review billing" } : null,
  ].filter(Boolean) as Array<{ title: string; detail: string; href: string; label: string }>;

  return <MemberShell eyebrow="Your Bantaba" title="Your private command center." description="A factual overview of your account, connections, and actions that need your attention. It never ranks you, scores your activity, or changes any state automatically.">
    <section className="welcome-panel"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-sm font-semibold text-gold">Your next meaningful step</p><h2 className="mt-3 max-w-3xl font-display text-4xl leading-tight text-cream">{eligibility?.profileComplete ? "Your foundation is ready to guide your next choice." : eligibility?.title || "Your profile is the first honest introduction."}</h2><p className="mt-4 max-w-3xl text-sm leading-6 text-cream/75">{eligibility?.profileComplete ? "Review thoughtful introductions, your privacy, and the status of your current connections at your own pace." : eligibility?.detail || "Build your private foundation before discovery begins."}</p></div><Badge className="border border-gold/30 bg-cream/10 text-cream">{member?.profileStatus?.replace(/_/g, " ") || "draft"}</Badge></div><div className="mt-7 flex flex-wrap gap-3"><Link href={eligibility?.profileComplete ? "/app/discover" : eligibility?.photosRemaining ? "/app/photos" : "/app/onboarding"} className="btn-gold inline-flex items-center gap-2">{eligibility?.profileComplete ? "Explore members" : eligibility?.nextAction || "Complete profile"}<ChevronRight size={16} /></Link><Link href="/app/profile/preview" className="inline-flex items-center gap-2 rounded-xl border border-cream/30 px-4 py-2.5 text-sm font-semibold text-cream hover:bg-cream/10">Preview your profile</Link></div></section>

    <section className="mt-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow text-gold-dark">Important actions</p><h2 className="mt-2 font-display text-3xl text-ink">What needs your attention</h2></div><Link href="/app/notifications" className="inline-flex items-center gap-2 text-sm font-semibold text-forest hover:underline"><BellRing size={16} />{unreadNotifications ? `${unreadNotifications} unread update${unreadNotifications === 1 ? "" : "s"}` : "Notification center"}</Link></div>{importantActions.length ? <div className="mt-5 grid gap-4 lg:grid-cols-2">{importantActions.map(action => <article key={action.title} className="surface-card border-gold/20"><div className="flex gap-3"><CircleAlert className="mt-1 shrink-0 text-gold-dark" size={20} /><div><h3 className="font-semibold text-ink">{action.title}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{action.detail}</p><Link href={action.href} className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-forest hover:underline">{action.label}<ChevronRight size={15} /></Link></div></div></article>)}</div> : <div className="mt-5 rounded-2xl border border-forest/10 bg-white p-5"><CheckCircle2 className="text-forest" size={22} /><p className="mt-3 font-semibold text-ink">No immediate account action is showing.</p><p className="mt-1 text-sm leading-6 text-muted-foreground">New private notifications will appear when a permitted event needs your attention. Discovery, safety, and relationship boundaries remain active in the background without an engagement score.</p></div>}</section>

    <section className="mt-7 grid gap-5 md:grid-cols-2 xl:grid-cols-4"><DashboardCard icon={Compass} eyebrow="Eligibility" title={eligibility?.profileComplete ? "Ready for discovery" : `${approvedPhotos}/5 approved photos`} detail={eligibility?.profileComplete ? "Your current profile foundation meets the available discovery criteria." : `${pendingPhotos ? `${pendingPhotos} photo${pendingPhotos === 1 ? " is" : "s are"} in review. ` : ""}${eligibility?.detail || "Complete each requirement at your pace."}`} href={eligibility?.profileComplete ? "/app/discover" : "/app/photos"} action={eligibility?.profileComplete ? "Open discovery" : "Review readiness"} />
      <DashboardCard icon={FileCheck2} eyebrow="Verification" title={verification.isError ? "Status unavailable" : latestVerification?.status === "approved" ? "Identity reviewed" : statusLabel(latestVerification?.status)} detail={verification.isError ? "Your verification result is not shown. Retry without changing any status." : latestVerification?.status === "approved" ? "A manual review approved your identity document." : "A document upload or review status never creates a badge by itself."} href="/app/verification" action="Open verification" />
      <DashboardCard icon={Lightbulb} eyebrow="Recommendations" title={recommendations.isError ? "Unavailable right now" : eligibility?.discoveryEligible ? `${recommendationCount} considered introduction${recommendationCount === 1 ? "" : "s"}` : "Profile not ready"} detail={recommendations.isError ? "No recommendation, feedback, or interest state changed." : eligibility?.discoveryEligible ? "These are privacy-safe starting points, never popularity or compatibility scores." : "Complete your available eligibility steps before recommendations can appear."} href="/app/recommendations" action="View recommendations" />
      <DashboardCard icon={MessageCircle} eyebrow="Connections" title={`${matches.data?.length ?? 0} mutual connection${(matches.data?.length ?? 0) === 1 ? "" : "s"}`} detail={conversations.isError ? "Conversation status is temporarily unavailable." : unreadMessages ? `${unreadMessages} unread message${unreadMessages === 1 ? "" : "s"}.` : "Readiness, voice, and video consent remain separate choices inside each connection."} href="/app/messages" action="Open messages" />
      <DashboardCard icon={UsersRound} eyebrow="Family Circle" title={family.isError ? "Status unavailable" : family.data?.length ? `${family.data.length} selected participant${family.data.length === 1 ? "" : "s"}` : "Optional and empty"} detail={family.isError ? "No Family Circle state is shown until you retry." : "Participants never receive private messages, documents, account control, relationship decisions, or call consent."} href="/app/family" action="Manage Family Circle" />
      <DashboardCard icon={CreditCard} eyebrow="Membership" title={billing.isError ? "Status unavailable" : membership?.level === "premium" ? "Premium conveniences" : "Bantabato Free"} detail={billing.isError ? "No membership or payment data is shown until you retry." : pendingRefund ? `${pendingRefund} refund request${pendingRefund === 1 ? " is" : "s are"} awaiting review.` : "Conveniences never override safety, privacy, consent, matching, verification, or Family Circle rules."} href="/app/billing" action="Review membership" />
      <DashboardCard icon={ShieldCheck} eyebrow="Safety" title={safety.isError ? "Safety status unavailable" : "Safety controls available"} detail={safety.isError ? "No safety state has been shown or changed. Retry when ready." : "Block, report, appeals, restrictions, and recovery remain private, scoped, and separate from matching or membership."} href="/app/safety" action="Open Safety Center" />
      <DashboardCard icon={HeartHandshake} eyebrow="Private milestone" title={declaration.isError ? "Status unavailable" : declaration.data?.outcome ? `Recorded as ${declaration.data.outcome}` : "Engaged or married?"} detail={declaration.isError ? "No declaration status is shown until you retry." : declaration.data?.outcome ? "This remains private unless separate editorial consent is submitted and approved." : "A private declaration never deletes or archives your account automatically."} href="/app/settings" action="Review milestone" />
    </section>

    <section className="mt-7 surface-card"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="eyebrow text-gold-dark">Connection readiness</p><h2 className="mt-2 font-display text-3xl text-ink">Consent stays specific.</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">Mutual connection permits private conversation only while the connection remains active. Voice and video readiness require their own current consent, can be withdrawn at any time, and do not activate a live calling service. A block, safety restriction, incompatibility, account state, or review hold removes the relevant path immediately.</p></div><Link href="/app/messages" className="inline-flex items-center gap-2 text-sm font-semibold text-forest hover:underline">Review connections<ChevronRight size={16} /></Link></div></section>
  </MemberShell>;
}

function DashboardCard({ icon: Icon, eyebrow, title, detail, href, action }: { icon: React.ComponentType<{ size?: number }>; eyebrow: string; title: string; detail: string; href: string; action: string }) { return <article className="surface-card"><div className="icon-plate"><Icon size={20} /></div><p className="mt-5 text-[11px] font-semibold uppercase tracking-[.12em] text-gold-dark">{eyebrow}</p><h3 className="mt-2 font-display text-2xl text-ink">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{detail}</p><Link href={href} className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-forest hover:underline">{action}<ChevronRight size={15} /></Link></article>; }
