import { MemberShell } from "@/components/MemberShell";
import { Button } from "@/components/ui/button";
import { useNetworkState } from "@/hooks/useDeviceExperience";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, ChevronRight, HeartHandshake, LockKeyhole, ShieldCheck, UsersRound } from "lucide-react";
import { Link } from "wouter";

export default function OnboardingWelcomePage() {
  const profile = trpc.profile.mine.useQuery();
  const network = useNetworkState();
  const started = Boolean(profile.data?.id);

  return <MemberShell eyebrow="Welcome" title="Begin at your own pace." description="Bantabato starts with a private foundation. No profile becomes eligible merely by signing in."><div className="mx-auto max-w-5xl space-y-7 motion-reveal">
    <section className="welcome-panel"><p className="text-sm font-semibold text-gold">A considered beginning</p><h2 className="mt-3 max-w-3xl font-display text-4xl leading-tight text-cream">Build a clear introduction before discovery begins.</h2><p className="mt-4 max-w-3xl text-sm leading-6 text-cream/75">Your next steps are deliberately separated: private profile foundations, five approved photos, manual identity review when you choose to submit a document, preferences, and then considered introductions when the server says the current requirements are met.</p><div className="mt-7 flex flex-wrap gap-3"><Button asChild className="btn-gold"><Link href="/app/onboarding">{started ? "Continue profile setup" : "Start private profile"}<ChevronRight size={16} /></Link></Button><Button asChild variant="outline" className="border-cream/35 bg-transparent text-cream hover:bg-cream/10 hover:text-cream"><Link href="/app/profile/preview">Understand profile preview</Link></Button></div></section>
    <section className="grid gap-5 md:grid-cols-3"><GuideCard icon={LockKeyhole} title="1. Private foundation" detail="Add only the core details you are ready to share. A device-local draft helps you recover from a refresh or temporary network loss; it is not a remote save until confirmed." /><GuideCard icon={ShieldCheck} title="2. Review with care" detail="Profile photos are reviewed under the existing five-approved-photo policy. Identity documents are private and manual review is never presented as a guaranteed badge." /><GuideCard icon={HeartHandshake} title="3. Mutual next steps" detail="Discovery, introductions, Family Circle invitations, and private communication each have their own consent, privacy, safety, and eligibility boundaries." /></section>
    <section className="surface-card"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow text-gold-dark">Read this guide</p><h2 className="mt-2 font-display text-3xl text-ink">Clear words remain the guide.</h2></div><UsersRound className="text-gold-dark" size={23} aria-hidden="true" /></div><div className="mt-5 grid gap-4 md:grid-cols-2"><div className="rounded-xl bg-cream/60 p-4"><p className="text-sm font-semibold text-ink">Marriage, place, and privacy</p><p className="mt-2 text-xs leading-5 text-muted-foreground">Core onboarding records the existing supported marital states and broad country context. More detailed Gambia, Senegal, diaspora, cross-border, long-distance, and location-visibility choices remain voluntary in International settings. Exact locations are not part of discovery.</p></div><div className="rounded-xl bg-cream/60 p-4"><p className="text-sm font-semibold text-ink">Family involvement remains optional</p><p className="mt-2 text-xs leading-5 text-muted-foreground">You may later invite a Parent or Wali/Guardian. They receive only the permissions you grant and never private messages, voice notes, identity documents, safety records, account controls, or call consent.</p></div></div><p className="mt-5 flex items-start gap-2 text-xs leading-5 text-muted-foreground"><CheckCircle2 className="mt-0.5 shrink-0 text-forest" size={15} />Audio guidance is not connected. This text guide is the accessible source of truth and keeps the entry experience low-bandwidth.</p>{network === "offline" ? <p role="status" className="mt-4 rounded-xl bg-gold/10 p-3 text-sm leading-6 text-gold-dark">You appear to be offline. You can read this guide, but secure sign-in and remote profile saving require reconnection. A draft is only created after you start the profile setup.</p> : null}</section>
  </div></MemberShell>;
}

function GuideCard({ icon: Icon, title, detail }: { icon: typeof LockKeyhole; title: string; detail: string }) { return <article className="surface-card"><Icon className="text-gold-dark" size={22} /><h2 className="mt-5 font-display text-2xl text-ink">{title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{detail}</p></article>; }
