import { MemberShell } from "@/components/MemberShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { StatePanel, StateSkeleton } from "@/components/StatePanel";
import { useNetworkState } from "@/hooks/useDeviceExperience";
import { trpc } from "@/lib/trpc";
import { Camera, ImagePlus, LockKeyhole, RefreshCcw } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function ProfileMediaPage() {
	  const photos = trpc.uploads.profilePhotos.useQuery();
	  const profile = trpc.profile.mine.useQuery();
	  const utils = trpc.useUtils();
	  const network = useNetworkState();
	  const upload = trpc.uploads.uploadProfilePhoto.useMutation({ onSuccess: () => { utils.uploads.profilePhotos.invalidate(); utils.profile.mine.invalidate(); setFile(null); toast.success("Your photo was uploaded privately."); }, onError: () => toast.error("We couldn’t upload that photo. Check your connection and retry; your selected file remains on this page.") });
	  const remove = trpc.uploads.removeProfilePhoto.useMutation({ onSuccess: () => { utils.uploads.profilePhotos.invalidate(); utils.profile.mine.invalidate(); toast.success("The photo was removed from your profile. You can choose a replacement when ready."); }, onError: () => toast.error("We couldn’t remove that photo right now. Nothing has changed; please try again.") });
  const [file, setFile] = useState<File | null>(null);
  const [selectionError, setSelectionError] = useState<string | null>(null);
	  const photoCount = photos.data?.length ?? 0;
	  const approvedPhotoCount = profile.data?.eligibility?.approvedPhotoCount ?? 0;
	  const pendingPhotoCount = profile.data?.completeness?.pendingPhotoCount ?? 0;
	  const remainingApprovedPhotos = profile.data?.eligibility?.photosRemaining ?? 5;
	  const atPhotoCapacity = photoCount >= 5;
	  const photoStatus = (status: string) => ({ pending: { label: "Pending review", detail: "Uploaded privately · awaiting review" }, approved: { label: "Approved", detail: "Counts toward your five approved photos" }, rejected: { label: "Action required", detail: "Review the note, then remove and replace this photo" } } as const)[status as "pending" | "approved" | "rejected"] ?? { label: status.replace(/_/g, " "), detail: "Private review status" };
  const selectFile = (candidate: File | null) => { setSelectionError(null); if (!candidate) { setFile(null); return; } if (atPhotoCapacity) { setFile(null); setSelectionError("You have added the maximum of 5 profile photos."); return; } if (!["image/jpeg", "image/png", "image/webp"].includes(candidate.type)) { setFile(null); setSelectionError("Choose a JPG, PNG, or WebP image."); return; } if (candidate.size > 8 * 1024 * 1024) { setFile(null); setSelectionError("This image is larger than 8 MB. Choose a smaller image and try again."); return; } setFile(candidate); };
	  const submit = async () => { if (!file) return; if (network === "offline") { toast.error("You appear to be offline. Keep this page open and retry after reconnecting."); return; } try { upload.mutate({ dataUrl: await readAsDataUrl(file) }); } catch { toast.error("We couldn’t read that image. Choose the file again and retry."); } };
	  if (photos.isLoading || profile.isLoading) return <MemberShell eyebrow="Profile photos" title="Photos, on your terms." description="Profile photos are separate from your verification selfie or identity document. You choose when profile photos become visible."><StateSkeleton label="Loading your private photo readiness…" /></MemberShell>;
	  if (photos.isError || profile.isError) return <MemberShell eyebrow="Profile photos" title="Photos, on your terms." description="Profile photos are separate from your verification selfie or identity document. You choose when profile photos become visible."><StatePanel kind="error" title="Your private photo area is unavailable right now." description="No photo or review state has been changed. Please try again." action={<Button onClick={() => { void photos.refetch(); void profile.refetch(); }} className="btn-forest">Try again</Button>} /></MemberShell>;
	  return <MemberShell eyebrow="Profile photos" title="Photos, on your terms." description="Profile photos are separate from your verification selfie or identity document. You choose when profile photos become visible.">
	    <div className="grid gap-7 xl:grid-cols-[1fr_.9fr]">
	      <section className="surface-card"><p className="eyebrow text-gold-dark">Profile readiness</p><h2 className="mt-3 font-display text-3xl">{approvedPhotoCount}/5 approved photos</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">You need 5 approved photos to complete your profile. {remainingApprovedPhotos ? `Add ${remainingApprovedPhotos} more photo${remainingApprovedPhotos === 1 ? "" : "s"} for review to continue.` : "Your approved-photo requirement is complete."}</p><div className="mt-7 grid grid-cols-5 gap-2">{Array.from({ length: 5 }, (_, index) => <div key={index} className={`grid aspect-square place-items-center rounded-xl ${index < approvedPhotoCount ? "bg-forest text-cream" : "border border-dashed border-forest/20 bg-cream text-gold-dark"}`}>{index < approvedPhotoCount ? <Camera size={16} /> : <span className="text-xs font-semibold">{index + 1}</span>}</div>)}</div>{pendingPhotoCount ? <p role="status" className="mt-4 text-sm leading-6 text-gold-dark">{pendingPhotoCount} photo{pendingPhotoCount === 1 ? " is" : "s are"} being reviewed. You can keep adding photos while slots remain.</p> : null}<div className="mt-7 rounded-2xl bg-cream p-5"><div className="flex gap-3"><LockKeyhole className="shrink-0 text-gold-dark" size={19} /><div><p className="text-sm font-semibold text-ink">Private by design</p><p className="mt-1 text-xs leading-5 text-muted-foreground">A profile photo is not automatically public. The visibility rule you select in Profile controls permitted viewing, and a verification image is never treated as a public photo.</p></div></div></div></section>
	      <section className="surface-card"><p className="eyebrow text-gold-dark">Secure upload</p><h2 className="mt-3 font-display text-3xl">Add or replace a profile photo.</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Choose a JPG, PNG, or WebP image up to 8 MB. Use the camera when your device offers it, or choose from your photo library. Uploaded photos are stored privately and await any required review.</p><input type="file" accept="image/jpeg,image/png,image/webp" capture="user" disabled={atPhotoCapacity} onChange={event => selectFile(event.target.files?.[0] ?? null)} className="mt-6 block w-full rounded-xl border border-dashed border-forest/20 bg-cream/50 px-3 py-3 text-sm text-muted-foreground file:mr-4 file:rounded-lg file:border-0 file:bg-forest file:px-3 file:py-2 file:text-xs file:font-semibold file:text-cream disabled:cursor-not-allowed disabled:opacity-60" />{atPhotoCapacity ? <p role="status" className="mt-3 text-sm text-gold-dark">Your five profile-photo slots are full. Remove a pending, rejected, or no-longer-wanted photo to open a private replacement slot.</p> : null}{file ? <p className="mt-3 text-xs text-forest">Selected: {file.name} · {(file.size / 1024 / 1024).toFixed(1)} MB</p> : null}{selectionError ? <p role="status" className="mt-3 text-sm text-destructive">{selectionError}</p> : null}<div className="mt-6 flex flex-wrap gap-3"><Button onClick={submit} disabled={!file || upload.isPending || network === "offline" || atPhotoCapacity} className="btn-forest">{upload.isPending ? "Uploading securely…" : upload.error ? "Retry secure upload" : "Add profile photo"} {upload.error ? <RefreshCcw size={16} /> : <ImagePlus size={16} />}</Button>{file && !upload.isPending ? <Button variant="outline" onClick={() => selectFile(null)}>Choose another</Button> : null}</div>{network === "offline" ? <p role="status" className="mt-3 text-sm text-gold-dark">You appear to be offline. The selected file stays only on this page until you reconnect.</p> : null}{upload.error ? <p className="mt-3 text-sm text-destructive">Upload not confirmed. Your selected file is still ready to retry.</p> : null}</section>
	    </div>
	    <section className="surface-card mt-7"><p className="eyebrow text-gold-dark">Private gallery</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Each slot shows a factual private review state. Removing a photo immediately stops its normal profile use and may change eligibility; it does not erase the review record.</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{photos.data?.length ? photos.data.map((photo, index) => { const status = photoStatus(photo.reviewStatus); return <article key={photo.id} className="rounded-2xl bg-cream p-4 text-center"><Camera size={19} className="mx-auto text-gold-dark" /><p className="mt-2 text-[10px] font-semibold uppercase tracking-[.1em] text-forest">Photo {index + 1}</p><Badge className="mt-2 badge-quiet">{status.label}</Badge><p className="mt-2 text-[10px] leading-4 text-muted-foreground">{status.detail}</p>{photo.reviewStatus === "rejected" && photo.reviewNote ? <p className="mt-2 text-[10px] leading-4 text-muted-foreground">{photo.reviewNote}</p> : null}<Button variant="outline" size="sm" className="mt-3 w-full" disabled={remove.isPending} onClick={() => { if (window.confirm(`Remove Photo ${index + 1} from your profile? This may change your profile readiness.`)) remove.mutate({ photoId: photo.id }); }}>{photo.reviewStatus === "rejected" ? "Remove & replace" : "Remove photo"}</Button></article>; }) : <p className="rounded-2xl bg-cream/60 p-5 text-sm leading-6 text-muted-foreground">No profile photos have been added yet. Start with a clear photo that feels true to you.</p>}</div></section>
  </MemberShell>;
}

function readAsDataUrl(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onerror = () => reject(new Error("The selected file could not be read")); reader.onload = () => resolve(String(reader.result)); reader.readAsDataURL(file); }); }
