import { MemberShell } from "@/components/MemberShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useNetworkState } from "@/hooks/useDeviceExperience";
import { trpc } from "@/lib/trpc";
import { Camera, ImagePlus, LockKeyhole, RefreshCcw } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function ProfileMediaPage() {
	  const photos = trpc.uploads.profilePhotos.useQuery();
	  const utils = trpc.useUtils();
	  const network = useNetworkState();
	  const upload = trpc.uploads.uploadProfilePhoto.useMutation({ onSuccess: () => { utils.uploads.profilePhotos.invalidate(); setFile(null); toast.success("Your photo was uploaded privately."); }, onError: () => toast.error("We couldn’t upload that photo. Check your connection and retry; your selected file remains on this page.") });
  const [file, setFile] = useState<File | null>(null);
  const [selectionError, setSelectionError] = useState<string | null>(null);
  const photoCount = photos.data?.length ?? 0;
  const atPhotoCapacity = photoCount >= 5;
  const selectFile = (candidate: File | null) => { setSelectionError(null); if (!candidate) { setFile(null); return; } if (atPhotoCapacity) { setFile(null); setSelectionError("You have added the maximum of 5 profile photos."); return; } if (!["image/jpeg", "image/png", "image/webp"].includes(candidate.type)) { setFile(null); setSelectionError("Choose a JPG, PNG, or WebP image."); return; } if (candidate.size > 8 * 1024 * 1024) { setFile(null); setSelectionError("This image is larger than 8 MB. Choose a smaller image and try again."); return; } setFile(candidate); };
	  const submit = async () => { if (!file) return; if (network === "offline") { toast.error("You appear to be offline. Keep this page open and retry after reconnecting."); return; } try { upload.mutate({ dataUrl: await readAsDataUrl(file) }); } catch { toast.error("We couldn’t read that image. Choose the file again and retry."); } };
  return <MemberShell eyebrow="Profile photos" title="Photos, on your terms." description="Profile photos are separate from your verification selfie or identity document. You choose when profile photos become visible.">
    <div className="grid gap-7 xl:grid-cols-[1fr_.9fr]">
      <section className="surface-card"><p className="eyebrow text-gold-dark">Profile gallery</p><h2 className="mt-3 font-display text-3xl">{photoCount} of 5 profile photos</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">Add up to five profile photos. This private gallery tracks the available slots; any separate discovery or review requirement remains controlled by the applicable policy, not by this display alone.</p><div className="mt-7 grid grid-cols-5 gap-2">{Array.from({ length: 5 }, (_, index) => <div key={index} className={`grid aspect-square place-items-center rounded-xl ${index < photoCount ? "bg-forest text-cream" : "border border-dashed border-forest/20 bg-cream text-gold-dark"}`}>{index < photoCount ? <Camera size={16} /> : <span className="text-xs font-semibold">{index + 1}</span>}</div>)}</div><div className="mt-7 rounded-2xl bg-cream p-5"><div className="flex gap-3"><LockKeyhole className="shrink-0 text-gold-dark" size={19} /><div><p className="text-sm font-semibold text-ink">Private by design</p><p className="mt-1 text-xs leading-5 text-muted-foreground">A profile photo is not automatically public. The visibility rule you select in Profile controls permitted viewing, and a verification image is never treated as a public photo.</p></div></div></div></section>
      <section className="surface-card"><p className="eyebrow text-gold-dark">Secure upload</p><h2 className="mt-3 font-display text-3xl">Add a profile photo.</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Choose a JPG, PNG, or WebP image up to 8 MB. Use the camera when your device offers it, or choose from your photo library. Uploaded photos are stored privately and await any required review.</p><input type="file" accept="image/jpeg,image/png,image/webp" capture="user" disabled={atPhotoCapacity} onChange={event => selectFile(event.target.files?.[0] ?? null)} className="mt-6 block w-full rounded-xl border border-dashed border-forest/20 bg-cream/50 px-3 py-3 text-sm text-muted-foreground file:mr-4 file:rounded-lg file:border-0 file:bg-forest file:px-3 file:py-2 file:text-xs file:font-semibold file:text-cream disabled:cursor-not-allowed disabled:opacity-60" />{atPhotoCapacity ? <p role="status" className="mt-3 text-sm text-gold-dark">Your five profile-photo slots are full.</p> : null}{file ? <p className="mt-3 text-xs text-forest">Selected: {file.name} · {(file.size / 1024 / 1024).toFixed(1)} MB</p> : null}{selectionError ? <p role="status" className="mt-3 text-sm text-destructive">{selectionError}</p> : null}<div className="mt-6 flex flex-wrap gap-3"><Button onClick={submit} disabled={!file || upload.isPending || network === "offline" || atPhotoCapacity} className="btn-forest">{upload.isPending ? "Uploading securely…" : upload.error ? "Retry secure upload" : "Add profile photo"} {upload.error ? <RefreshCcw size={16} /> : <ImagePlus size={16} />}</Button>{file && !upload.isPending ? <Button variant="outline" onClick={() => selectFile(null)}>Choose another</Button> : null}</div>{network === "offline" ? <p role="status" className="mt-3 text-sm text-gold-dark">You appear to be offline. The selected file stays only on this page until you reconnect.</p> : null}{upload.error ? <p className="mt-3 text-sm text-destructive">Upload not confirmed. Your selected file is still ready to retry.</p> : null}</section>
    </div>
    <section className="surface-card mt-7"><p className="eyebrow text-gold-dark">Private gallery</p><div className="mt-5 flex flex-wrap gap-3">{photos.data?.length ? photos.data.map((photo, index) => <div key={photo.id} className="flex h-24 w-24 flex-col items-center justify-center rounded-2xl bg-cream text-center"><Camera size={19} className="text-gold-dark" /><p className="mt-2 text-[10px] font-semibold uppercase tracking-[.1em] text-forest">Photo {index + 1}</p><Badge className="mt-1 badge-quiet">{photo.reviewStatus}</Badge></div>) : <p className="rounded-2xl bg-cream/60 p-5 text-sm leading-6 text-muted-foreground">No profile photos have been added yet. Start with a clear photo that feels true to you.</p>}</div></section>
  </MemberShell>;
}

function readAsDataUrl(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onerror = () => reject(new Error("The selected file could not be read")); reader.onload = () => resolve(String(reader.result)); reader.readAsDataURL(file); }); }
