import { PublicLayout } from "@/components/PublicLayout";
import { Button } from "@/components/ui/button";
import { StatePanel, StateSkeleton } from "@/components/StatePanel";
import { trpc } from "@/lib/trpc";
import { ArrowRight, HeartHandshake, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

export default function PublicSuccessStoriesPage() {
  const stories = trpc.publicContent.successStories.useQuery();
  return <PublicLayout><main className="public-page"><div className="container max-w-5xl"><div className="max-w-3xl"><p className="eyebrow text-gold-dark">Member stories</p><h1 className="mt-5 font-display text-5xl leading-[1.02] text-ink md:text-6xl">A Bantabato story has taken root.</h1><p className="mt-7 text-lg leading-8 text-muted-foreground">These are voluntary, reviewed stories shared only after explicit consent and independent approval. They are personal milestones, not promises or proof that Bantabato guarantees an outcome.</p></div>{stories.isLoading ? <StateSkeleton label="Loading voluntary member stories" /> : stories.isError ? <StatePanel className="mt-12" kind="error" title="Stories are unavailable right now." description="Nothing has been changed. Please try again in a moment." action={<Button onClick={() => stories.refetch()} className="btn-forest">Try again</Button>} /> : stories.data?.length ? <div className="mt-12 grid gap-6 md:grid-cols-2">{stories.data.map((story, index) => <article key={`${story.publishedAt?.toString() ?? index}-${index}`} className="surface-card"><HeartHandshake className="text-gold-dark" size={22} /><p className="mt-6 font-display text-3xl leading-tight text-ink">{story.story}</p><div className="mt-7 flex items-center justify-between gap-4 border-t border-forest/10 pt-5 text-sm"><span className="font-semibold text-forest">{story.displayName || "Shared with name withheld"}</span><span className="text-muted-foreground">{story.outcome === "engaged" ? "Engagement" : "Marriage"}</span></div></article>)}</div> : <StatePanel className="mt-12" kind="empty" title="Stories are shared only when a member chooses." description="There are no voluntary, fully approved public stories to share right now. Private milestones remain private unless the member follows the full consent and review process." />}<section className="mt-12 rounded-[1.6rem] border border-forest/10 bg-cream/60 p-7"><p className="eyebrow text-gold-dark">Respectful by design</p><h2 className="mt-3 font-display text-3xl text-ink">Privacy remains part of every story.</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-muted-foreground">This page never displays private messages, family information, contact details, verification material, private location, safety information, or original private profile media. A member can withdraw their story at any time, which removes it from normal public presentation.</p><Button asChild className="mt-7 btn-forest"><Link href="/how-it-works">Learn how Bantabato works <ArrowRight size={16} /></Link></Button></section></div></main></PublicLayout>;
}
