import { PublicLayout } from "@/components/PublicLayout";
import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { ArrowRight, CheckCircle2, Mail, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

const content: Record<string, { eyebrow: string; title: string; intro: string; sections: { heading: string; body: string }[] }> = {
  about: { eyebrow: "Our approach", title: "A shared table for serious conversations.", intro: "Bantabato takes its name from the Gambian Bantaba: a place for gathering, listening, and meaningful decisions. We bring that spirit to a modern, private matrimonial space.", sections: [{ heading: "Marriage-first", body: "The platform is designed for adults who want a lasting marriage, not casual dating. Members are invited to state their intentions and preferences with care." }, { heading: "Faith and cultural dignity", body: "Bantabato welcomes Muslim and Christian Gambians while giving every member room to describe their own practice, values, and family background." }, { heading: "A global Gambian community", body: "Members can represent whether they are in The Gambia or the diaspora, creating a single, connected community without splitting the experience." }] },
  "how-it-works": { eyebrow: "How it works", title: "A thoughtful process, from first step to first conversation.", intro: "Each part of Bantabato is designed to help members move with care, confidence, and mutual respect.", sections: [{ heading: "1. Create a considered profile", body: "Begin with the essentials: your background, faith, location, marriage intention, and what you hope to find. You decide what to reveal and when." }, { heading: "2. Verify your identity", body: "Identity verification is reviewed manually. A badge is only awarded after approval; no automated verification claim is made before that review is complete." }, { heading: "3. Express interest respectfully", body: "A member may send an introduction request. A private conversation is available only after the recipient accepts and a match is formed." }, { heading: "4. Involve family by choice", body: "A member can invite a parent or wali to receive match notifications. This never grants automatic access to private conversations." }] },
  safety: { eyebrow: "Safety & verification", title: "Trust is not a feature. It is the foundation.", intro: "Bantabato combines careful member controls with clear moderation pathways. Safety tools are available throughout the member experience.", sections: [{ heading: "Manual verification", body: "ID verification is designed for human review. A verified badge reflects an approved identity-document review, not an unverified upload or development state." }, { heading: "Control in every interaction", body: "Members can report or block profiles and conversations. Reports enter a structured review queue for the Trust & Safety team." }, { heading: "Privacy by default", body: "Profile visibility, photo visibility, search inclusion, and family visibility are separate choices. Members can keep photos hidden until a mutual match is established." }] },
  privacy: { eyebrow: "Privacy", title: "Your information, on your terms.", intro: "Matrimonial information can be sensitive. Bantabato is structured so a member can make deliberate choices about their profile and their family context.", sections: [{ heading: "Layered profile visibility", body: "Members can choose a public, members-only, or hidden profile. Individual photo and family visibility options are kept separate from general profile visibility." }, { heading: "Sensitive documents", body: "Verification documents are never treated as public profile content. The platform data model keeps verification storage references distinct from public photos." }, { heading: "Meaningful access boundaries", body: "Private messages are restricted to active mutual matches. A family contact receives only the notifications a member has explicitly permitted." }] },
  terms: { eyebrow: "Terms", title: "A respectful community requires shared standards.", intro: "The Phase 1 experience communicates the standards that guide membership. Formal legal terms should be reviewed and approved by Bantabato’s legal counsel before public launch.", sections: [{ heading: "Membership intent", body: "Bantabato is intended for serious adults seeking marriage. Misrepresentation, harassment, fraud, or attempts to misuse the platform are not acceptable." }, { heading: "Verification and moderation", body: "Verification reviews and safety reports are subject to appropriate internal review processes. A verification badge is never guaranteed by simply submitting a document." }, { heading: "Before launch", body: "This foundation includes the route and presentation structure for terms. Production legal text, data-retention terms, and dispute processes remain a launch prerequisite." }] },
  contact: { eyebrow: "Contact", title: "We are listening.", intro: "For early access, operations, safety, or partnership enquiries, the Bantabato team can be reached through the formal contact channel once it is configured for launch.", sections: [{ heading: "Member support", body: "The member application includes foundations for reports, notifications, and an administrative support area. A public support mailbox has not yet been connected." }, { heading: "Safety concerns", body: "If you experience harm or urgent risk, use the in-app report and block tools when available. Immediate local emergency concerns should be directed to appropriate local services." }] },
};

export function PublicInfoPage({ page }: { page: keyof typeof content }) {
  const item = content[page];
  return <PublicLayout><main className="public-page"><div className="container max-w-4xl"><p className="eyebrow text-gold-dark">{item.eyebrow}</p><h1 className="mt-5 font-display text-5xl leading-[1.02] text-ink md:text-6xl">{item.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-muted-foreground">{item.intro}</p><div className="mt-14 space-y-10">{item.sections.map(section => <section key={section.heading} className="content-block"><CheckCircle2 size={20} className="mt-1 shrink-0 text-gold-dark" /><div><h2 className="font-display text-3xl text-ink">{section.heading}</h2><p className="mt-3 leading-7 text-muted-foreground">{section.body}</p></div></section>)}</div><div className="mt-16 flex flex-col justify-between gap-5 rounded-[1.75rem] bg-forest px-7 py-8 sm:flex-row sm:items-center"><div><p className="font-display text-2xl text-cream">Begin your journey with care.</p><p className="mt-1 text-sm text-cream/65">A space designed for commitment, not swiping.</p></div><Button asChild className="btn-gold"><Link href="/register">Join Bantabato <ArrowRight size={16} /></Link></Button></div></div></main></PublicLayout>;
}

export function FAQPage() { const questions = [{ q: "Is Bantabato a dating app?", a: "No. Bantabato is a marriage-first matrimonial platform. Discovery is deliberately considered and there is no swipe-first experience." }, { q: "Who can join?", a: "The Phase 1 eligibility framework supports adults aged 18–60, including people who have never married, are divorced, or are widowed. Final launch criteria remain configurable in the business-rule layer." }, { q: "Can I hide my photos?", a: "Yes. Photo visibility is a separate choice. Members can keep photos hidden until a mutual match has been established." }, { q: "Will my family see my messages?", a: "No. Family involvement is optional and scoped. A designated wali or parent can receive match notifications only when the member has consented; private conversations stay private." }, { q: "How does verification work?", a: "Identity verification is designed for manual review. A badge is only awarded after an administrator approves a valid identity-document submission." }]; return <PublicLayout><main className="public-page"><div className="container max-w-3xl"><p className="eyebrow text-gold-dark">FAQ</p><h1 className="mt-5 font-display text-5xl text-ink md:text-6xl">Clear answers, before you begin.</h1><div className="mt-14 divide-y divide-forest/10 rounded-[1.5rem] border border-forest/10 bg-white px-6">{questions.map(item => <section key={item.q} className="py-7"><h2 className="font-display text-2xl text-ink">{item.q}</h2><p className="mt-3 leading-7 text-muted-foreground">{item.a}</p></section>)}</div></div></main></PublicLayout>; }

export function SignInPage({ registration }: { registration?: boolean }) { return <PublicLayout><main className="public-page"><div className="container grid min-h-[62vh] place-items-center"><div className="w-full max-w-md rounded-[2rem] border border-forest/10 bg-white p-8 shadow-[0_20px_60px_rgba(21,58,45,.08)]"><div className="rounded-2xl bg-gold/12 p-4 text-gold-dark w-fit"><ShieldCheck size={26} /></div><p className="mt-7 text-xs font-semibold uppercase tracking-[.16em] text-gold-dark">{registration ? "Begin with intention" : "Welcome back"}</p><h1 className="mt-3 font-display text-4xl text-ink">{registration ? "Create your private member space." : "Continue your journey."}</h1><p className="mt-4 text-sm leading-6 text-muted-foreground">{registration ? "Sign in securely to begin your onboarding. Your profile remains a draft until you choose to submit it." : "Sign in securely to access your profile, matches, and private conversations."}</p><Button onClick={() => startLogin()} className="mt-8 w-full btn-forest h-12">{registration ? "Create account / sign in" : "Sign in securely"} <ArrowRight size={16} /></Button><p className="mt-5 text-center text-xs leading-5 text-muted-foreground">By continuing, you acknowledge the platform’s community standards and privacy-first approach.</p></div></div></main></PublicLayout>; }

export function ContactPage() { return <PublicLayout><main className="public-page"><div className="container max-w-3xl"><p className="eyebrow text-gold-dark">Contact</p><h1 className="mt-5 font-display text-5xl text-ink md:text-6xl">We are listening.</h1><div className="mt-10 rounded-[1.5rem] border border-forest/10 bg-white p-8"><Mail className="text-gold-dark" /><h2 className="mt-5 font-display text-3xl text-ink">Contact channel pending launch setup.</h2><p className="mt-3 leading-7 text-muted-foreground">The public enquiry channel will be configured when Bantabato selects its support service. In the meantime, prospective members can review the platform approach, safety standards, and FAQ.</p><Link href="/faq" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-forest">Read the FAQ <ArrowRight size={16} /></Link></div></div></main></PublicLayout>; }
