import { PublicLayout } from "@/components/PublicLayout";
import { Button } from "@/components/ui/button";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { startLogin } from "@/const";
import { ArrowRight, CheckCircle2, CircleHelp, HeartHandshake, LockKeyhole, Mail, MessageCircleWarning, ShieldCheck, UserRoundCheck, UsersRound } from "lucide-react";
import { Link } from "wouter";

type PublicPageKey = "about" | "how-it-works" | "family" | "safety" | "privacy" | "terms";
type InfoSection = { heading: string; body: string };
type InfoPage = { eyebrow: string; title: string; intro: string; sections: InfoSection[]; cta: { label: string; href: string } };

const content: Record<PublicPageKey, InfoPage> = {
  about: { eyebrow: "Our approach", title: "A shared table for serious conversations.", intro: "Bantabato takes its name from the Gambian Bantaba: a place for gathering, listening, and meaningful decisions. We bring that spirit to a modern, private matrimonial space.", cta: { label: "See how Bantabato works", href: "/how-it-works" }, sections: [{ heading: "Marriage-first, not swipe-first", body: "Bantabato is designed for adults who want a lasting marriage, not casual dating. Members are invited to state their intentions and preferences with care, while the other person remains free to decide." }, { heading: "Cultural dignity and personal agency", body: "The product is shaped for Gambians at home and abroad, including Muslim and Christian communities, without assuming a member’s individual practice, values, family background, or preferred level of family involvement." }, { heading: "Responsible technology", body: "Bantabato does not use a Trust Score, popularity ranking, or paid matching advantage. Verification, privacy, safety, and communication remain protected by their own boundaries." }] },
  "how-it-works": { eyebrow: "How it works", title: "A thoughtful process, from first step to first conversation.", intro: "Each part of Bantabato is designed to help members move with care, privacy, and mutual respect.", cta: { label: "Begin with intention", href: "/register" }, sections: [{ heading: "A private profile foundation", body: "Members begin with a profile, privacy choices, intentions, and preferences. An incomplete profile remains a draft and does not become eligible merely by signing in." }, { heading: "Readiness and review", body: "The member experience explains the relevant readiness steps, including private identity-document review and approved-photo requirements where applicable. A submission is not an approval." }, { heading: "Mutual connection before communication", body: "A respectful introduction may be expressed, but private conversation opens only after a mutual connection and any relevant access checks. A member can report, block, or withdraw according to the product’s safety boundaries." }] },
  family: { eyebrow: "Family Circle", title: "Family involvement, held with care.", intro: "A member can invite a trusted parent or wali/guardian when it feels right. Participation is optional, scoped, and remains under the member’s control.", cta: { label: "Explore privacy choices", href: "/privacy" }, sections: [{ heading: "Invitation and acknowledgement", body: "Only the member can create, resend, manage, or revoke a Family Circle invitation. A recipient accepts their own account-bound invitation and can acknowledge shared match information only within that limited role." }, { heading: "Consent is never assumed", body: "The member chooses whether to involve a Parent or Wali/Guardian and can change permissions, withdraw a shared match, remove a participant, or revoke a pending invitation. Family participation is not required to use Bantabato." }, { heading: "Purpose-specific privacy", body: "A Parent or Wali/Guardian receives only the permissioned match and acknowledgement information the member allows. Family Circle never grants automatic access to private conversations, voice notes, identity documents, safety reports, billing records, or unrestricted profile details. It is not a route around member consent." }] },
  safety: { eyebrow: "Safety, privacy & verification", title: "Trust is not a feature. It is a practice.", intro: "Bantabato combines manual review, private controls, mutual communication, and structured reporting pathways. These measures can reduce risk; they cannot guarantee another person’s character, intentions, compatibility, or safety.", cta: { label: "Read privacy choices", href: "/privacy" }, sections: [{ heading: "Manual verification, clearly limited", body: "Identity verification exists to review a private identity-document submission. An Identity reviewed badge means that review was approved. It does not make a safety promise, assess compatibility, rank a member, or disclose a document." }, { heading: "Private documents and media", body: "Identity documents stay separate from public photos, discovery, recommendations, messages, Family Circle information, and ordinary staff summaries. Private media is accessed only through the appropriate authorized boundary; no public document link or storage key is shown." }, { heading: "Control in every interaction", body: "Members can manage profile and photo visibility, report or block profiles and conversations, and use account controls. Reports enter a structured review process; public pages never reveal report details, staff notes, or private safety decisions." }] },
  privacy: { eyebrow: "Privacy choices", title: "Your information, on your terms.", intro: "Matrimonial information can be sensitive. Bantabato is structured so a member can make deliberate choices about profile presentation, family context, and communication.", cta: { label: "See Family Circle boundaries", href: "/family-circle" }, sections: [{ heading: "Controlled discovery", body: "Profile visibility, photo visibility, search inclusion, and Family Circle visibility are separate choices. Country selections are used as reciprocal eligibility inputs, not a precise-location disclosure or popularity signal." }, { heading: "Private by design", body: "Private identity documents, private media, messages, voice, safety records, payment details, and Family Circle content are isolated from public profiles, public stories, discovery, recommendations, and ordinary staff summaries." }, { heading: "Communication and account control", body: "Private messages remain behind active mutual-match and safety boundaries. Members have reporting, blocking, visibility, notification, and account controls; a Family Circle participant receives only the scoped information the member has permitted." }] },
  terms: { eyebrow: "Member standards", title: "A respectful community requires shared standards.", intro: "Bantabato’s current public standards describe the respectful, marriage-first boundaries that shape the member experience.", cta: { label: "Read the FAQ", href: "/faq" }, sections: [{ heading: "Membership intent", body: "Bantabato is intended for serious adults seeking marriage. Misrepresentation, harassment, fraud, or attempts to misuse another member’s information are not acceptable." }, { heading: "Consent and safety", body: "Verification is not guaranteed by an upload. Communication, Family Circle participation, and private information are subject to consent, eligibility, safety, and authorization boundaries." }, { heading: "Public foundation", body: "This route shares product standards, not legal advice or a launch claim. Formal legal terms, retention terms, and applicable dispute processes require separate review before any future public launch." }] },
};

const howSteps = [
  ["1", "Create your profile", "Begin with a private profile, clear intentions, and preferences."],
  ["2", "Follow readiness steps", "Complete the factual profile, photo, and review steps that apply to you."],
  ["3", "Discover thoughtfully", "Consider compatible members without a public social feed or swipe-first mechanic."],
  ["4", "Express interest", "Make an introduction respectfully; the other member always decides."],
  ["5", "Connect when it is mutual", "Private conversation becomes available only after the connection is mutual."],
  ["6", "Build toward marriage", "Continue at your pace, with optional Family Circle or Wali involvement."],
] as const;

export function PublicInfoPage({ page }: { page: PublicPageKey }) {
  const item = content[page];
  const pageIcon = page === "family" ? UsersRound : page === "safety" ? ShieldCheck : page === "privacy" ? LockKeyhole : HeartHandshake;
  const PageIcon = pageIcon;
  return <PublicLayout><main className="public-page"><div className="container max-w-5xl"><div className="grid gap-8 lg:grid-cols-[1fr_.48fr]"><div><p className="eyebrow text-gold-dark">{item.eyebrow}</p><h1 className="mt-5 max-w-4xl font-display text-5xl leading-[1.02] text-ink md:text-6xl">{item.title}</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-muted-foreground">{item.intro}</p></div><aside className="rounded-[1.6rem] border border-forest/10 bg-white p-6 shadow-[0_14px_38px_rgba(21,58,45,.05)]"><div className="icon-plate"><PageIcon size={22} /></div><p className="mt-6 text-sm leading-6 text-muted-foreground">Public guidance is intentionally factual. Private member information, review records, documents, and sensitive account state are never shown here.</p><Link href="/contact" className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-forest">Need support guidance? <ArrowRight size={16} /></Link></aside></div>
    {page === "how-it-works" ? <ol className="mt-14 grid gap-4 md:grid-cols-2">{howSteps.map(([number, title, body]) => <li key={number} className="rounded-[1.35rem] border border-forest/10 bg-white p-6"><span className="text-xs font-semibold uppercase tracking-[.16em] text-gold-dark">Step {number}</span><h2 className="mt-3 font-display text-3xl text-ink">{title}</h2><p className="mt-3 text-sm leading-7 text-muted-foreground">{body}</p></li>)}</ol> : null}
    <div className="mt-14 grid gap-5 md:grid-cols-3">{item.sections.map((section, index) => <section key={section.heading} className="rounded-[1.5rem] border border-forest/10 bg-white p-6"><CheckCircle2 size={20} className="text-gold-dark" /><p className="mt-6 text-xs font-semibold uppercase tracking-[.14em] text-gold-dark">{String(index + 1).padStart(2, "0")}</p><h2 className="mt-2 font-display text-3xl leading-tight text-ink">{section.heading}</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">{section.body}</p></section>)}</div>
    <section className="mt-12 flex flex-col justify-between gap-5 rounded-[1.75rem] bg-forest px-7 py-8 sm:flex-row sm:items-center"><div><p className="font-display text-2xl text-cream">Begin your journey with care.</p><p className="mt-1 text-sm text-cream/65">A space designed for commitment, privacy, and mutual respect.</p></div><Button asChild className="btn-gold"><Link href={item.cta.href}>{item.cta.label} <ArrowRight size={16} /></Link></Button></section>
  </div></main></PublicLayout>;
}

const questions = [
  ["What is Bantabato?", "Bantabato is a marriage-first matrimonial platform for adults who want to move toward marriage with care, privacy, and mutual respect. It is not a swipe-first dating product."],
  ["Who can join?", "The product’s current eligibility framework supports adults aged 18–60, including people who have never married, are divorced, or are widowed. Eligibility is determined privately in the member experience; this public page cannot confirm anyone’s account status."],
  ["Which countries does Bantabato currently present for?", "Bantabato currently presents its member journey for people connected to The Gambia, Senegal, and the diaspora. Country choices support reciprocal eligibility; they do not reveal precise location or create a popularity ranking."],
  ["How does verification work?", "A member submits a private identity document through the member experience, and an authorized reviewer assesses it manually. An approved review may show an Identity reviewed badge. Uploading a document is not approval."],
  ["What does an Identity reviewed badge not mean?", "It is not a safety guarantee, a statement about character or marriage intentions, a compatibility assessment, or a ranking signal. It simply reflects an approved identity-document review."],
  ["Are my documents and private media public?", "No. Identity documents are kept out of discovery, profiles, recommendations, messages, Family Circle information, and public stories. Private media stays behind its applicable authorized access boundary."],
  ["Why are photos part of readiness?", "The member experience uses five approved photos as part of its factual readiness policy. If an approved photo is removed, readiness and downstream profile presentation are recalculated through the product’s server-authoritative rules."],
  ["Can I hide my photos or control discovery?", "Yes. Profile visibility, photo visibility, search inclusion, and Family Circle visibility are separate member choices. Some changes may affect whether or how a profile can participate in discovery."],
  ["Will my family or wali see my messages?", "No. Family Circle is optional and scoped. A designated Parent or Wali/Guardian never receives automatic access to private conversations, voice notes, identity documents, safety information, or billing records."],
  ["How do interests and communication work?", "A member may express interest respectfully. Private conversation becomes available only after both people form a mutual connection and relevant access checks remain satisfied."],
  ["Can I report or block someone?", "The member experience includes report and block controls for profiles and conversations. Reports enter a structured internal review process; public pages do not show private case information or staff notes."],
  ["Is Bantabato currently free?", "Yes. Bantabato is currently free during the initial launch period. Core access does not require a subscription, payment method, checkout, or paid status."],
  ["Can payment change my access?", "No current payment path is available. Eligibility, privacy, identity review, approved-photo readiness, consent, compatibility, Family Circle permissions, relationship state, and Safety Center rules remain mandatory and cannot be purchased around."],
  ["How are public stories chosen?", "Only a voluntary story that remains consented, independently approved, and currently published may appear publicly. A withdrawal removes normal public presentation; private messages, source media, safety information, and documents are never shown."],
  ["Can I control or close my account?", "Account-specific controls are available only after secure sign-in. Public pages do not reveal whether an account exists, its eligibility, or any private status."],
] as const;

export function FAQPage() { return <PublicLayout><main className="public-page"><div className="container max-w-4xl"><p className="eyebrow text-gold-dark">FAQ</p><h1 className="mt-5 font-display text-5xl leading-[1.02] text-ink md:text-6xl">Clear answers, before you begin.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">The answers below describe the current product boundaries without exposing private member information or making promises Bantabato cannot keep.</p><Accordion type="single" collapsible className="mt-12 rounded-[1.5rem] border border-forest/10 bg-white px-6 sm:px-8">{questions.map(([question, answer], index) => <AccordionItem key={question} value={`faq-${index}`}><AccordionTrigger className="py-6 font-display text-xl text-ink hover:no-underline sm:text-2xl">{question}</AccordionTrigger><AccordionContent className="max-w-3xl pb-6 text-sm leading-7 text-muted-foreground">{answer}</AccordionContent></AccordionItem>)}</Accordion><section className="mt-10 rounded-[1.5rem] border border-forest/10 bg-cream/65 p-7"><CircleHelp className="text-gold-dark" size={22} /><h2 className="mt-5 font-display text-3xl text-ink">Still deciding?</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-muted-foreground">Explore the safety, privacy, and Family Circle boundaries before you create a private profile. This public guidance does not start sign-in or create an account.</p><div className="mt-6 flex flex-wrap gap-3"><Button asChild className="btn-forest"><Link href="/safety">Safety & privacy <ArrowRight size={16} /></Link></Button><Button asChild variant="outline" className="border-forest/20 bg-white text-forest"><Link href="/family-circle">Family Circle</Link></Button></div></section></div></main></PublicLayout>; }

export function MembershipPage() {
  return <PublicLayout><main className="public-page"><div className="container"><div className="max-w-3xl"><p className="eyebrow text-gold-dark">Membership</p><h1 className="mt-5 font-display text-5xl leading-[1.02] text-ink md:text-6xl">A trusted platform for meaningful marriage connections.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-muted-foreground">Bantabato is currently free during our initial launch period. Core access does not require a subscription, payment method, checkout, or paid status.</p></div><section className="mt-12 grid gap-6 lg:grid-cols-2"><MembershipCard title="Free during initial launch" eyebrow="Current access" description="Create a private profile, follow readiness steps, discover thoughtfully, connect mutually, and use the core Bantabato journey without payment." benefits={["Profile, privacy, and discovery controls", "Verification submission and five-photo readiness", "Discovery, compatibility, recommendations, and messaging", "Family Circle, safety, support, notifications, and data rights"]} cta /><section className="surface-card"><p className="eyebrow text-gold-dark">Commercial status</p><h2 className="mt-3 font-display text-4xl text-ink">Billing is dormant for now.</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">Provider-neutral billing architecture is retained for a possible future release. No payment provider is active, no checkout is available, and no commercial obligation is created during the initial launch period.</p><div className="mt-7 rounded-xl bg-cream/65 p-4 text-sm leading-6 text-muted-foreground"><p><strong className="text-ink">Current access:</strong> Free</p><p><strong className="text-ink">Payment provider:</strong> Not active</p><p><strong className="text-ink">Checkout:</strong> Unavailable during Free Launch</p></div></section></section><section className="mt-8 rounded-[1.6rem] border border-forest/10 bg-white p-7"><p className="eyebrow text-gold-dark">Non-negotiable protections</p><h2 className="mt-3 font-display text-3xl text-ink">Free does not mean unverified or unsafe.</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-muted-foreground">Eligibility, privacy, identity review, approved-photo readiness, consent, compatibility, Family Circle permissions, relationship state, and Safety Center rules remain mandatory. Free access never buys a match, visibility, approval, or exemption.</p></section></div></main></PublicLayout>;
}

function MembershipCard({ title, eyebrow, description, benefits, cta = false }: { title: string; eyebrow: string; description: string; benefits: string[]; cta?: boolean }) { return <section className="surface-card"><p className="eyebrow text-gold-dark">{eyebrow}</p><h2 className="mt-3 font-display text-4xl text-ink">{title}</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">{description}</p><ul className="mt-7 space-y-3 text-sm leading-6 text-muted-foreground">{benefits.map(item => <li key={item} className="flex gap-2"><CheckCircle2 className="mt-0.5 shrink-0 text-forest" size={16} />{item}</li>)}</ul>{cta ? <Button asChild className="mt-8 btn-forest"><Link href="/register">Begin with intention <ArrowRight size={16} /></Link></Button> : null}</section>; }

export function SignInPage({ registration }: { registration?: boolean }) {
  const joining = Boolean(registration);
  return <PublicLayout><main className="public-page"><div className="container grid min-h-[62vh] items-center py-4"><section className="signup-entry-grid"><div className="signup-intro-panel"><div className="signup-intro-orbit" aria-hidden="true"><span /><span /><span /></div><p className="eyebrow text-gold">{joining ? "A considered beginning" : "Welcome back"}</p><h1 className="mt-5 max-w-md font-display text-5xl leading-[.98] text-cream md:text-6xl">{joining ? "A private space to begin with intention." : "Your journey remains yours to guide."}</h1><p className="mt-6 max-w-md text-sm leading-7 text-cream/72">{joining ? "Bantabato is built for serious adults who want to move toward marriage with clarity, privacy, and mutual respect." : "Return to your profile, introductions, and private conversations through the same secure sign-in boundary."}</p><ul className="signup-principles" aria-label="What to expect"><li><CheckCircle2 size={16} /> Your profile begins as a private draft.</li><li><CheckCircle2 size={16} /> Discovery is thoughtful, not swipe-first.</li><li><CheckCircle2 size={16} /> You choose your pace and privacy.</li></ul></div><div className="signup-action-panel"><div className="icon-plate"><ShieldCheck size={23} /></div><p className="mt-7 text-xs font-semibold uppercase tracking-[.16em] text-gold-dark">{joining ? "Secure entry" : "Private return"}</p><h2 className="mt-3 font-display text-4xl text-ink">{joining ? "Start your profile foundation." : "Continue your journey."}</h2><p className="mt-4 text-sm leading-6 text-muted-foreground">{joining ? "Secure sign-in creates or opens your member account, then guides you through Essentials, Life & marriage, and Privacy. Your incomplete profile remains a draft and cannot become eligible by simply signing in." : "Sign in securely to access your profile, introductions, and private conversations."}</p>{joining ? <ol className="mt-6 space-y-3 rounded-xl bg-cream p-4 text-sm text-muted-foreground"><li><strong className="text-ink">1. Secure entry</strong> · Sign in through the account boundary.</li><li><strong className="text-ink">2. Private profile draft</strong> · Save or return to your device-local onboarding draft.</li><li><strong className="text-ink">3. Readiness steps</strong> · Complete profile, photos, preferences, and review requirements at your own pace.</li></ol> : null}<Button onClick={() => startLogin()} className="mt-8 h-12 w-full btn-forest">{joining ? "Create account / sign in" : "Sign in securely"} <ArrowRight size={16} /></Button><p className="mt-5 rounded-xl bg-cream p-4 text-xs leading-5 text-muted-foreground">If secure sign-in cannot finish, no profile, payment, verification, or membership state has changed—return here and try again. Offline access cannot complete sign-in, but your onboarding draft stays only on your device after you begin. Restricted or eligibility-specific information is shown only after secure account access.</p></div></section></div></main></PublicLayout>;
}

const supportCards = [
  [CircleHelp, "General questions", "Start with clear public answers about membership, photos, countries, Family Circle, and communication.", "Read the FAQ", "/faq"],
  [UserRoundCheck, "Account support", "Account-specific help is available only after secure sign-in. This protects account existence and private member status.", "Secure member entry", "/login"],
  [MessageCircleWarning, "Safety concerns", "Review the in-app reporting and blocking boundary. For urgent local risk, contact appropriate local emergency services.", "Safety guidance", "/safety"],
  [LockKeyhole, "Privacy requests", "Understand profile visibility, private documents and media, communication, and Family Circle privacy choices.", "Privacy guidance", "/privacy"],
] as const;

export function ContactPage() { return <PublicLayout><main className="public-page"><div className="container max-w-5xl"><p className="eyebrow text-gold-dark">Contact & support</p><h1 className="mt-5 max-w-3xl font-display text-5xl leading-[1.02] text-ink md:text-6xl">Find the right kind of guidance.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-muted-foreground">Bantabato does not currently send public enquiries through an external support provider. The guidance below is available now and does not transmit personal information.</p><div className="mt-12 grid gap-5 md:grid-cols-2">{supportCards.map(([Icon, title, body, label, href]) => <article key={title} className="rounded-[1.5rem] border border-forest/10 bg-white p-7"><Icon size={22} className="text-gold-dark" /><h2 className="mt-5 font-display text-3xl text-ink">{title}</h2><p className="mt-3 text-sm leading-7 text-muted-foreground">{body}</p><Link href={href} className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-forest">{label} <ArrowRight size={16} /></Link></article>)}</div><section className="mt-10 rounded-[1.5rem] border border-gold/25 bg-cream/70 p-7"><Mail className="text-gold-dark" size={22} /><h2 className="mt-5 font-display text-3xl text-ink">Public message delivery is not configured.</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-muted-foreground">No email, ticket, form submission, external support message, or provider delivery is initiated from this page. When a member needs account-specific help, secure entry keeps the request within the private product boundary.</p></section></div></main></PublicLayout>; }
