import { MemberShell } from "@/components/MemberShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Switch } from "@/components/ui/switch";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, ChevronRight, Compass, HeartHandshake, Lightbulb, MapPin, Settings2, ShieldCheck, SlidersHorizontal, UsersRound } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { Link } from "wouter";

const categories = [
  { value: "all", label: "Recommended for you" },
  { value: "strong_compatibility", label: "Strong compatibility" },
  { value: "similar_marriage_goals", label: "Similar marriage goals" },
  { value: "verified_members", label: "Verified members" },
  { value: "recently_joined", label: "Recently joined" },
  { value: "worth_exploring", label: "Worth exploring" },
] as const;

type Feedback = "not_interested" | "not_relevant" | "already_considered" | "hide_profile";

export default function RecommendationsPage() {
  const [category, setCategory] = useState<(typeof categories)[number]["value"]>("all");
  const [selected, setSelected] = useState<number | null>(null);
  const utils = trpc.useUtils();
  const queryInput = useMemo(() => ({ limit: 12, category: category === "all" ? undefined : category }), [category]);
  const recommendations = trpc.recommendations.list.useQuery(queryInput);
  const settings = trpc.recommendations.settings.useQuery();
  const explanation = trpc.recommendations.explain.useQuery({ recommendationId: selected ?? 1 }, { enabled: selected !== null });
  const feedback = trpc.recommendations.feedback.useMutation({ onSuccess: () => { utils.recommendations.list.invalidate(); toast.success("Your feedback was saved for your discovery experience."); }, onError: error => toast.error(error.message) });
  const startInterest = trpc.recommendations.startInterest.useMutation({ onSuccess: () => { utils.recommendations.list.invalidate(); toast.success("Your introduction request was sent through the existing mutual-interest process."); }, onError: error => toast.error(error.message) });
  const saveSettings = trpc.recommendations.saveSettings.useMutation({ onSuccess: () => { utils.recommendations.settings.invalidate(); utils.recommendations.list.invalidate(); toast.success("Recommendation settings updated."); }, onError: error => toast.error(error.message) });
  const changeSetting = (key: "recommendationsEnabled" | "showVerifiedCategory" | "showNearbyCategory" | "showRecentCategory", value: boolean) => {
    if (!settings.data) return;
    saveSettings.mutate({ recommendationsEnabled: settings.data.recommendationsEnabled, showVerifiedCategory: settings.data.showVerifiedCategory, showNearbyCategory: settings.data.showNearbyCategory, showRecentCategory: settings.data.showRecentCategory, [key]: value });
  };

  return <MemberShell eyebrow="Smart matching" title="Meaningful introductions, explained." description="These recommendations use your stated preferences, privacy boundaries, and marriage intent. They are not popularity rankings, compatibility percentages, or decisions about who you should marry.">
    <section className="welcome-panel"><Lightbulb size={25} className="text-gold" /><p className="mt-6 text-xs font-semibold uppercase tracking-[.16em] text-gold">A considered starting point</p><h2 className="mt-3 max-w-3xl font-display text-3xl text-cream">Potential fit is something to explore—not a verdict.</h2><p className="mt-4 max-w-3xl text-sm leading-6 text-cream opacity-80">Safety, profile visibility, blocks, and stated hard requirements are checked before any profile reaches this page. Voice and video readiness remain separate, mutual-consent decisions.</p></section>

    <section className="mt-7 surface-card"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="eyebrow text-gold-dark">Your recommendation lens</p><h2 className="mt-2 font-display text-2xl text-ink">Choose a thoughtful set</h2></div><Link href="/app/compatibility" className="inline-flex items-center gap-2 text-sm font-semibold text-forest hover:underline"><SlidersHorizontal size={16} />Review stated preferences</Link></div><div className="mt-5 flex flex-wrap gap-2">{categories.map(item => <Button key={item.value} variant={category === item.value ? "default" : "outline"} className={category === item.value ? "btn-forest" : ""} onClick={() => setCategory(item.value)}>{item.label}</Button>)}</div></section>

    <section className="mt-7"><div className="mb-5 flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow text-gold-dark">Potential introductions</p><h2 className="mt-2 font-display text-3xl text-ink">{category === "all" ? "Recommended for you" : categories.find(item => item.value === category)?.label}</h2></div><p className="max-w-sm text-sm leading-6 text-muted-foreground">The page shows plain-language context instead of a score. A difference can be worth discussing; it is not a judgment or automatic rejection.</p></div>{recommendations.isLoading ? <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3"><LoadingCard /><LoadingCard /><LoadingCard /></div> : recommendations.data?.items.length ? <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{recommendations.data.items.map(item => <RecommendationCard key={item.id} item={item} onExplain={() => setSelected(item.id)} onFeedback={response => feedback.mutate({ recommendationId: item.id, response })} onInterest={() => startInterest.mutate({ recommendationId: item.id })} disabled={feedback.isPending || startInterest.isPending} />)}</div> : <EmptyRecommendationState />}</section>

    <section className="mt-7 surface-card"><div className="flex flex-wrap items-start justify-between gap-6"><div><p className="eyebrow text-gold-dark">Recommendation settings</p><h2 className="mt-2 font-display text-2xl text-ink">Keep discovery on your terms.</h2><p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">Turning recommendations off only changes your own discovery feed. It does not change an existing mutual interest, message, Family Circle permission, or connection-readiness state.</p></div><Settings2 className="text-gold-dark" /></div><div className="mt-6 grid gap-3 md:grid-cols-2">{settings.isLoading ? <div className="h-24 animate-pulse rounded-xl bg-forest/8" /> : <><SettingRow label="Show recommendations" description="Receive your private, considered introduction sets." checked={settings.data?.recommendationsEnabled ?? true} onCheckedChange={value => changeSetting("recommendationsEnabled", value)} /><SettingRow label="Show verified-member category" description="Treat identity review as information about account authenticity, not human worth." checked={settings.data?.showVerifiedCategory ?? true} onCheckedChange={value => changeSetting("showVerifiedCategory", value)} /><SettingRow label="Show nearby category" description="Use country-level location only; exact addresses are never used." checked={settings.data?.showNearbyCategory ?? true} onCheckedChange={value => changeSetting("showNearbyCategory", value)} /><SettingRow label="Show recently joined category" description="Recency is secondary to compatibility and never a popularity signal." checked={settings.data?.showRecentCategory ?? true} onCheckedChange={value => changeSetting("showRecentCategory", value)} /></>}</div></section>

    <section className="mt-7 rounded-2xl border border-forest/10 bg-white px-5 py-5"><div className="flex gap-3"><UsersRound className="mt-0.5 shrink-0 text-gold-dark" size={20} /><div><h2 className="font-semibold text-ink">Family Circle remains member-led.</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">A recommended profile does not automatically become visible to a Parent or Wali/Guardian. Existing Family Circle sharing remains available only through its permissioned, mutual-match path.</p></div></div></section>

    <Dialog open={selected !== null} onOpenChange={open => !open && setSelected(null)}><DialogContent className="max-w-lg"><DialogHeader><DialogTitle className="font-display text-3xl text-ink">Why you are seeing this</DialogTitle><DialogDescription>These are privacy-safe conversation starters based only on information you are allowed to see.</DialogDescription></DialogHeader>{explanation.isLoading ? <div className="h-28 animate-pulse rounded-xl bg-forest/8" /> : <div className="space-y-4">{explanation.data?.explanations.map(text => <div key={text} className="rounded-xl bg-forest/5 p-4 text-sm leading-6 text-forest">{text}</div>)}{explanation.data?.considerations.map(text => <div key={text} className="rounded-xl border border-gold/25 bg-gold/5 p-4 text-sm leading-6 text-ink">{text}</div>)}<p className="text-xs leading-5 text-muted-foreground">{explanation.data?.note}</p><p className="text-xs font-medium text-gold-dark">Policy version: {explanation.data?.policyVersion}</p></div>}</DialogContent></Dialog>
  </MemberShell>;
}

function RecommendationCard({ item, onExplain, onFeedback, onInterest, disabled }: { item: { id: number; profileId: number; categoryKey: string; displayName: string | null; city: string | null; country: string | null; residenceType: "gambia" | "diaspora"; photoVisibility: "public" | "mutual_match" | "hidden"; identityVerified: boolean; explanations: string[]; considerations: string[] }; onExplain: () => void; onFeedback: (response: Feedback) => void; onInterest: () => void; disabled: boolean }) {
  return <article className="discovery-card"><div className="discovery-portrait"><Compass size={24} /><span>{item.photoVisibility === "public" ? "Profile photo follows member privacy" : "Photos remain protected by member privacy"}</span></div><div className="p-5"><div className="flex items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-display text-2xl text-ink">{item.displayName || "Bantabato member"}</h3>{item.identityVerified ? <Badge className="badge-quiet"><CheckCircle2 size={13} />Identity reviewed</Badge> : null}</div><p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground"><MapPin size={12} />{[item.city, item.country].filter(Boolean).join(", ") || (item.residenceType === "gambia" ? "The Gambia" : "Gambian diaspora")}</p></div><ShieldCheck className="text-gold-dark" size={19} /></div><Badge variant="outline" className="mt-5 border-forest/15 text-xs text-forest">{item.categoryKey.replace(/_/g, " ")}</Badge>{item.explanations[0] ? <div className="mt-4 rounded-xl bg-forest/5 p-3"><p className="text-[11px] font-semibold uppercase tracking-[.12em] text-gold-dark">Potential alignment</p><p className="mt-1 text-xs leading-5 text-forest">{item.explanations[0]}</p></div> : <div className="mt-4 rounded-xl bg-cream p-3 text-xs leading-5 text-muted-foreground">View the privacy-safe explanation before deciding whether to explore this introduction.</div>}{item.considerations[0] ? <p className="mt-3 text-xs leading-5 text-muted-foreground">{item.considerations[0]}</p> : null}<div className="mt-5 grid gap-2"><Button variant="outline" onClick={onExplain}>See why this appeared <ChevronRight size={16} /></Button><Link href={`/app/profile/${item.profileId}`} className="inline-flex items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-sm font-semibold text-forest hover:bg-forest/5">View considered profile <ChevronRight size={16} /></Link><Button className="btn-forest" onClick={onInterest} disabled={disabled}><HeartHandshake size={16} />Send an introduction request</Button><div className="flex flex-wrap gap-x-3 gap-y-2 pt-1 text-xs font-semibold text-muted-foreground"><button disabled={disabled} onClick={() => onFeedback("not_interested")} className="hover:text-forest">Not interested</button><button disabled={disabled} onClick={() => onFeedback("not_relevant")} className="hover:text-forest">Not relevant</button><button disabled={disabled} onClick={() => onFeedback("already_considered")} className="hover:text-forest">Already considered</button><button disabled={disabled} onClick={() => onFeedback("hide_profile")} className="hover:text-forest">Hide profile</button></div></div></div></article>;
}

function SettingRow({ label, description, checked, onCheckedChange }: { label: string; description: string; checked: boolean; onCheckedChange: (value: boolean) => void }) { return <div className="flex items-start justify-between gap-4 rounded-xl border border-forest/10 bg-cream/35 p-4"><div><p className="font-semibold text-ink">{label}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{description}</p></div><Switch checked={checked} onCheckedChange={onCheckedChange} /></div>; }
function LoadingCard() { return <div className="h-80 animate-pulse rounded-[1.5rem] bg-forest/8" />; }
function EmptyRecommendationState() { return <div className="empty-state"><div className="icon-plate"><Compass size={25} /></div><h2 className="mt-6 font-display text-3xl text-ink">No introductions are available in this set.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-muted-foreground">This can reflect your privacy-safe filters, stated hard requirements, existing blocks, or the current eligible member pool. You can adjust a preference without compromising what matters to you.</p><Link href="/app/compatibility" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-forest">Review compatibility preferences <ChevronRight size={16} /></Link></div>; }
